### ISSUE TITLE
Incompatible AnyCable RPC client

### ISSUE THREAD

**Issue by matedemorphy** [anycable/anycable#101]
When try to start the server: `bundle exec anycable --server-command "anycable-go --host=localhost --port=3334"` it returns this error:`status:13:Incompatible AnyCable RPC client.` and the method `connect` in `connection.rb` is not even called. I'm using 1.0.0.rc2 version.

**Comment by Envek** [comment]
Most probably you have installed old version of anycable-go websocket server (e.g. 0.6.x).

Try to install [version 1.0.0](https://github.com/anycable/anycable-go/releases/tag/v1.0.0) of anycable-go. With Homebrew you can do it via `brew install --HEAD anycable-go`.

See https://github.com/anycable/anycable-rails/issues/132 for more details
