### ISSUE TITLE
Websocket disconnects while sending uint8Array data.

### ISSUE THREAD

**Issue by x8BitRain** [anycable/anycable#103]
### Tell us about your environment

**Ruby version:**
2.6.6
**`anycable` gem version:**
0.6.5
**`grpc` gem version:**
1.17
### What did you do?
Tried to send a uint8array from client to server.
### What did you expect to happen?
The server should have received and stored the sent data.
### What actually happened?
The upload stops mid way through and the websocket connection resets itself (disconnects and reconnects automatically).

I'm trying to send binary (uint8Array) data over a websocket from browser to server...
The websocket connection will disconnect and reconnect automatically without any error after sending the binary data and then terminating the upload before it finishes.
My theory is that the ping message received from the server every 3 seconds is interrupted by the data upload so the client tries to reset the  connection when it doesn't receive the ping message on time.
Is this accurate or could it be something to do with the size being too large or something else?

Here is a server log from Rails.
Line 19 is where the disconnect happens while receiving the data.
https://pastebin.com/80k3vT5W 
edit: 
https://github.com/anycable/anycable/files/4908585/anycablelog.txt

**Comment by palkan** [comment]
> Line 19 is where the disconnect happens while receiving the data.
https://pastebin.com/80k3vT5W

Looks like the link has expired (I see 502).

Could you also take a look at the anycable-go logs, ideally, with `ANYCABLE_DEBUG=true`?

**Comment by x8BitRain** [comment]
Here's the same log, it should also include anycable-go log lines.
[anycablelog.txt](https://github.com/anycable/anycable/files/4908585/anycablelog.txt)

**Comment by palkan** [comment]
This file doesn't include logs for `anycable-go`. As far as I can see, it prints logs to stdout.
Try redirecting `anycable-go` logs to a file, e.g., `anycable-go ... > log/anycable.log`.

**Comment by palkan** [comment]
Closed as stale.
