### ISSUE TITLE
RPC Connect nil

### ISSUE THREAD

**Issue by tak1n** [anycable/anycable#105]
### Tell us about your environment

**Ruby version:** 2.7.1

**`anycable` gem version:** 1.0.1

**`grpc` gem version:** 1.30.1

### What did you do?

Added exception handler for anycable grpc instances according to doc https://docs.anycable.io/#/v1/ruby/exceptions. I guess this is not the culprit here but I just got aware after checking the logs and still seeing that no sentry errors are appearing.

### What did you expect to happen?

Sentry errors appearing and RPC connections being properly established.

### What actually happened?

```
D, [2020-07-21T22:48:59.561456 #8] DEBUG -- : [AnyCable sid=_aJk9rA79LnZuEfP-1GmV] RPC Connect: nil
I, [2020-07-21T22:48:59.568989 #8]  INFO -- : [AnyCable sid=_aJk9rA79LnZuEfP-1GmV] Sending event e152428270da4a4b8f79a20903fce2a7 to Sentry
E, [2020-07-21T22:48:59.707319 #8] ERROR -- : [AnyCable sid=_aJk9rA79LnZuEfP-1GmV] undefined method `env' for nil:NilClass
```
This does not happen for all gRPC connections. There are various problems in the go websocket part according to our logs as well:

```
D 2020-07-21T22:41:50.155Z context=ws Websocket connection upgrade error: "websocket: the client is not using the websocket protocol: 'upgrade' token not found in 'Connection' header"
D 2020-07-21T21:33:37.289Z context=node sid=khA1x6VyRAhgllT8xScZa Websocket close error: websocket: close 1006 (abnormal closure): unexpected EOF
```

I guess the first can be neglected as it could be some misbehaviour of some client or our proxy/load-balancer. Any suggestions I can help to debug this further? I assume Sentry Raven internally relies on a `env` method (maybe `Rails.env`?), but without a stacktrace which I currently don't know how to get its quite hard to tell.

I've set `LOG_LEVEL` to `debug` on the grpc instances and `ANYCABLE_DEBUG` to `true` on websocket instances.

**Comment by tak1n** [comment]
Ah sry I've missed that `ANYCABLE_DEBUG` is as well available on the gRPC instances, I've set it and see the following now in the logs:

```
E, [2020-07-21T23:03:39.510683 #9] ERROR -- : [AnyCable sid=50oTNCPV7rW-NizZJp2qm] undefined method `env' for nil:NilClass:
/home/onlim/chatbot_service/vendor/bundle/ruby/2.6.6/ruby/2.6.0/gems/anycable-1.0.1/lib/anycable/rpc_handler.rb:16:in `connect'
/home/onlim/chatbot_service/vendor/bundle/ruby/2.6.6/ruby/2.6.0/gems/grpc-1.30.1-x86_64-linux/src/ruby/lib/grpc/generic/rpc_desc.rb:60:in `call'
/home/onlim/chatbot_service/vendor/bundle/ruby/2.6.6/ruby/2.6.0/gems/grpc-1.30.1-x86_64-linux/src/ruby/lib/grpc/generic/rpc_desc.rb:60:in `block in handle_request_response'
/home/onlim/chatbot_service/vendor/bundle/ruby/2.6.6/ruby/2.6.0/gems/grpc-1.30.1-x86_64-linux/src/ruby/lib/grpc/generic/interceptors.rb:178:in `block (2 levels) in intercept!'
/home/onlim/chatbot_service/vendor/bundle/ruby/2.6.6/ruby/2.6.0/gems/grpc-1.30.1-x86_64-linux/src/ruby/lib/grpc/generic/interceptors.rb:178:in `block (2 levels) in intercept!'
/home/onlim/chatbot_service/vendor/bundle/ruby/2.6.6/ruby/2.6.0/gems/grpc-1.30.1-x86_64-linux/src/ruby/lib/grpc/generic/interceptors.rb:181:in `block in intercept!'
/home/onlim/chatbot_service/vendor/bundle/ruby/2.6.6/ruby/2.6.0/gems/anycable-1.0.1/lib/anycable/middleware.rb:14:in `block in request_response'
/home/onlim/chatbot_service/vendor/bundle/ruby/2.6.6/ruby/2.6.0/gems/anycable-rails-1.0.1/lib/anycable/rails/middlewares/log_tagging.rb:16:in `block in call'
/home/onlim/chatbot_service/vendor/bundle/ruby/2.6.6/ruby/2.6.0/gems/activesupport-6.0.3.2/lib/active_support/tagged_logging.rb:80:in `block in tagged'
/home/onlim/chatbot_service/vendor/bundle/ruby/2.6.6/ruby/2.6.0/gems/activesupport-6.0.3.2/lib/active_support/tagged_logging.rb:28:in `tagged'
/home/onlim/chatbot_service/vendor/bundle/ruby/2.6.6/ruby/2.6.0/gems/activesupport-6.0.3.2/lib/active_support/tagged_logging.rb:80:in `tagged'
/home/onlim/chatbot_service/vendor/bundle/ruby/2.6.6/ruby/2.6.0/gems/anycable-rails-1.0.1/lib/anycable/rails/middlewares/log_tagging.rb:16:in `call'
/home/onlim/chatbot_service/vendor/bundle/ruby/2.6.6/ruby/2.6.0/gems/anycable-1.0.1/lib/anycable/middleware.rb:13:in `request_response'
/home/onlim/chatbot_service/vendor/bundle/ruby/2.6.6/ruby/2.6.0/gems/grpc-1.30.1-x86_64-linux/src/ruby/lib/grpc/generic/interceptors.rb:175:in `intercept!'
/home/onlim/chatbot_service/vendor/bundle/ruby/2.6.6/ruby/2.6.0/gems/grpc-1.30.1-x86_64-linux/src/ruby/lib/grpc/generic/interceptors.rb:177:in `block in intercept!'
/home/onlim/chatbot_service/vendor/bundle/ruby/2.6.6/ruby/2.6.0/gems/anycable-1.0.1/lib/anycable/middleware.rb:14:in `block in request_response'
/home/onlim/chatbot_service/vendor/bundle/ruby/2.6.6/ruby/2.6.0/gems/anycable-rails-1.0.1/lib/anycable/rails/middlewares/executor.rb:16:in `block in call'
/home/onlim/chatbot_service/vendor/bundle/ruby/2.6.6/ruby/2.6.0/gems/activesupport-6.0.3.2/lib/active_support/execution_wrapper.rb:88:in `wrap'
/home/onlim/chatbot_service/vendor/bundle/ruby/2.6.6/ruby/2.6.0/gems/activesupport-6.0.3.2/lib/active_support/reloader.rb:72:in `block in wrap'
/home/onlim/chatbot_service/vendor/bundle/ruby/2.6.6/ruby/2.6.0/gems/activesupport-6.0.3.2/lib/active_support/execution_wrapper.rb:88:in `wrap'
```

So its actually anycable related code which throws an exception here, as far as I can tell because the gRPC connection is `nil`. Still wonder why we get no Sentry error altough it states its sending the event (guess unrelated to anycable).

**Comment by palkan** [comment]
> RPC Connect: nil

Looks like we somehow getting here: https://github.com/grpc/grpc/blob/172f61a3a257257ce84394a87708b0d11aa7001b/src/ruby/lib/grpc/generic/active_call.rb#L266-L267

Does this error happen often?

**Comment by tak1n** [comment]
> Does this error happen often?

Since fixing sentry (was a problem on our on premise instance) it is being reported ~ 240 times/hour. It also seems quite constant in the number of appearances per hour, so maybe its caused by a uptime check we have in place :thinking:

**Comment by palkan** [comment]
And what is your RPC calls per hour?

Any other errors at the anycable-go side? (especially, with `context=rpc` tag)

**Comment by tak1n** [comment]
> And what is your RPC calls per hour?

During the day its ~ 60k per hour according to our datadog dashboard:

![rpc_total](https://user-images.githubusercontent.com/675705/88166671-ec5c2f80-cc17-11ea-9e18-501e68024c21.png)

> Any other errors at the anycable-go side? (especially, with context=rpc tag)

Nope no errors with `context=rpc` as far as I see. Not sure if following output is somehow related to the problem (just tried to search for null on anycable-go side)
```
D 2020-07-22T10:33:27.457Z context=rpc Authenticate response: status:SUCCESS identifiers:"{}" transmissions:"{\"type\":\"welcome\"}" env:<cstate:<key:"__ltags__" value:"null" > > 
```

**Comment by palkan** [comment]
Interesting. So, the ratio of invalid calls is pretty small. Couldn't find anything related in the gRPC repo Issues but I guess that could be something related to networking or deadlines.

What is your concurrency settings (rpc_pool_size for AnyCable RPC and rpc_concurrency for ancybale-go) and the total number of RPC/WS servers?

> our datadog dashboard:

Awesome! Do you use Prometheus metrics endpoint for that or what?

What about `anycable_go_rpc_error_total` and `anycable_go_rpc_retries_total` stats?

**Comment by tak1n** [comment]
> What is your concurrency settings (rpc_pool_size for AnyCable RPC and rpc_concurrency for ancybale-go) and the total number of RPC/WS servers?

We are using the default values of `30` for `rpc_pool_size` and `28` for `rpc_concurrency`. 3 RPC and WS server are running.

> Awesome! Do you use Prometheus metrics endpoint for that or what?

Yes :)

> What about anycable_go_rpc_error_total and anycable_go_rpc_retries_total stats?

![rpc_error_total](https://user-images.githubusercontent.com/675705/88169289-13b4fb80-cc1c-11ea-803d-7a0792109fd4.png)

`anycable_go_rpc_retries_total` we don't export yet it seems, I will talk with my co-workers so we also get this metric visible.

**Comment by palkan** [comment]
> 3 RPC and WS server are running

You mean 3 RPCs and 3 WS or 3 RPCs and 1 WS?

Do you have a load balancer for RPCs?

**Comment by tak1n** [comment]
> You mean 3 RPCs and 3 WS or 3 RPCs and 1 WS?

Sry for not being clear, yes 3 WS and 3 RPCs. We are running on kubernetes, issue https://github.com/anycable/anycable-go/issues/83 is from my co-worker. So we are running Cloudflare as Load Balancer, Kong as Proxy/Gateway for the websocket instances and for RPC we rely on kubernetes balancing it.

I just saw that 1 RPC pod is sitting idle and not receiving any connections/commands, going to restart it and see what happens:
```
[INFO] Start Onlim worker

I, [2020-07-21T23:02:54.490529 #8]  INFO -- sentry: ** [Raven] Raven 2.13.0 ready to catch errors
W, [2020-07-21T23:02:56.295505 #8]  WARN -- : Creating scope :active. Overwriting existing method Assignment.active.
I, [2020-07-21T23:02:56.526632 #8]  INFO -- : Starting AnyCable gRPC server (pid: 8, workers_num: 30)
I, [2020-07-21T23:02:56.526679 #8]  INFO -- : AnyCable version: 1.0.1 (proto_version: v1)
I, [2020-07-21T23:02:56.526700 #8]  INFO -- : gRPC version: 1.30.1
I, [2020-07-21T23:02:56.526713 #8]  INFO -- : Serving Rails application from ./config/environment.rb
I, [2020-07-21T23:02:56.527266 #8]  INFO -- : handling /anycable.RPC/Connect with #<Method: AnyCable::RPCHandler#connect>
I, [2020-07-21T23:02:56.527298 #8]  INFO -- : handling /anycable.RPC/Command with #<Method: AnyCable::RPCHandler#command>
I, [2020-07-21T23:02:56.527341 #8]  INFO -- : handling /anycable.RPC/Disconnect with #<Method: AnyCable::RPCHandler#disconnect>
I, [2020-07-21T23:02:56.527372 #8]  INFO -- : handling /grpc.health.v1.Health/Check with #<Method: Grpc::Health::Checker#check>
I, [2020-07-21T23:02:56.527393 #8]  INFO -- : handling /grpc.health.v1.Health/Watch with #<Method: Grpc::Health::Checker(Grpc::Health::V1::Health::Service)#watch>
I, [2020-07-21T23:02:56.527922 #8]  INFO -- : Broadcasting Redis channel: __anycable__
I, [2020-07-21T23:02:56.527948 #8]  INFO -- : RPC server is starting...
I, [2020-07-21T23:02:56.543746 #8]  INFO -- : RPC server is listening on 0.0.0.0:50051
```

**Comment by tak1n** [comment]
> I just saw that 1 RPC pod is sitting idle

I assume it is some configuration error on our side as we use anycable since quite some while before https://docs.anycable.io/#/v1/deployment/kubernetes was available/documented.

**Comment by tak1n** [comment]
Okay I think we have to look more in depth on how todo gRPC load balancing as it is stated in various articles the default kubernetes load balancing only works well with connection based load balancing (HTTP 1.1, HTTP1).

- https://learnk8s.io/kubernetes-long-lived-connections
- https://kubernetes.io/blog/2018/11/07/grpc-load-balancing-on-kubernetes-without-tears/

Shouldn't be related to the problem described here though right? Sorry for so many comments, I'm just trying to understand all concepts somewhat better :sweat_smile:

**Comment by palkan** [comment]
> Shouldn't be related to the problem described here though right?

It's actually could be, because the problem looks like something network related. Maybe, k8s load balancer has some kind of timeout of whatever and it drops grpc connections in the middle of the calls.

Hey, @Envek, you know k8s much better than me 😀 Any thoughts ^?

**Comment by Envek** [comment]
No, AFAIK pure Kubernetes services (that doesn't backed by provider-specific things) doesn't have any timeouts (it is just set of iptables rules)

**Comment by tak1n** [comment]
Just short heads up, the exceptions disappeared and we have no idea why :mage_woman: 

Total RPC Errors:

![rpc_error2](https://user-images.githubusercontent.com/675705/88198480-06136c00-cc44-11ea-973b-c55f231c33c9.png)

Sentry errors:

![sentry](https://user-images.githubusercontent.com/675705/88197890-60f89380-cc43-11ea-8a41-fd9179d412e4.png)

anycable-rpc pods were recreated at Wed, Jul 22, 2020 2:04 PM, at 2:19 PM the last sentry error was reported as well as the last RPC errors. Should I close the issue as we can't really reproduce the issue or even know what caused it?

**Comment by palkan** [comment]
> Should I close the issue as we can't really reproduce the issue or even know what caused it?

Let's wait for a day or two.

> pods were recreated

How ofter are they usually recreated? Maybe, that's somehow related to deployments frequency.

**Comment by tak1n** [comment]
> How ofter are they usually recreated? Maybe, that's somehow related to deployments frequency.

On every deploy, which isn't that often in production for us. Altough since seeing this error they (both `anycable-go` and `anycable-rpc` pods) were as well multiple times recreated as I've changed the env vars eg `ANYCABLE_DEBUG` and `LOG_LEVEL` and as well played around with how many pods are running at a time (upscale/downscale). So no idea why with the last recreation it seemingly fixed it.

**Comment by palkan** [comment]
@tak1n Any updates? Have you seen this issue again?

**Comment by tak1n** [comment]
@palkan nope, didn't happen again.

I will close the issue, thx for your help so far :v:
