### ISSUE TITLE
Unable to add defs to DescriptorPool

### ISSUE THREAD

**Issue by Sexual** [anycable/anycable#11]
Ruby 2.4.0p0
Latest gem version
Latest anycable-go binary

Attempting to use it for the first time and when running the `rails g anycable` command, I get this error:

```
/home/vagrant/.rvm/gems/ruby-2.4.0@global/gems/bundler-1.13.7/lib/bundler/runtime.rb:94:in `rescue in block (2 levels) in require': There was an error while trying to load the gem 'anycable'. (Bundler::GemRequireError)
Gem Load Error is: Unable to add defs to DescriptorPool: Symtab already has a def named 'anycable.ConnectionRequest_MapEntry_headers'

```

**Comment by palkan** [comment]
Sorry for late response(

Looks like `anycable` gem is **loaded** twice. Do you use Spring or other preloader?

**Comment by Sexual** [comment]
Nope, maybe I'll try add `require: false`.

**Comment by Sexual** [comment]
That didn't fix it @palkan

**Comment by palkan** [comment]
Can you show me your Gemfile? Or, it would be great, if you share the whole application code with me.
I cannot reproduce it(

**Comment by Sexual** [comment]
Cannot provide the application but can provide the Gemfile.


`source 'https://rubygems.org'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
# Full-stack web application framework. (https://www.rubyonrails.org)
gem 'rails'
# Use mysql2 as the database for Active Record
# A simple, fast Mysql library for Ruby, binding to libmysql (https://github.com/brianmario/mysql2)
gem 'mysql2'
# Use SCSS for stylesheets
# Sass adapter for the Rails asset pipeline. (https://github.com/rails/sass-rails)
gem 'sass-rails'
# Use Uglifier as compressor for JavaScript assets
# Ruby wrapper for UglifyJS JavaScript compressor (http://github.com/lautis/uglifier)
gem 'uglifier'
# Use CoffeeScript for .js.coffee assets and views
# CoffeeScript adapter for the Rails asset pipeline. (https://github.com/rails/coffee-rails)
gem 'coffee-rails'
# Use jQuery with Rails 4+ (http://rubygems.org/gems/jquery-rails)
gem 'jquery-rails'
# Turbolinks makes following links in your web application faster (use with Rails Asset Pipeline) (https://github.com/rails/turbolinks/)
# Turbolinks makes navigating your web application faster (https://github.com/turbolinks/turbolinks-rails)
gem 'turbolinks'
# Pagination plugin for web frameworks and other apps (https://github.com/mislav/will_paginate/wiki)
gem 'will_paginate'
# Flexible authentication solution for Rails with Warden (https://github.com/plataformatec/devise)
gem 'devise'
# Slim progress bars for Ajax'y applications. Inspired by Google, YouTube, and Medium. (https://github.com/caarlos0/nprogress-rails)
gem 'nprogress-rails'
# Puma is a simple, fast, threaded, and highly concurrent HTTP 1.1 server for Ruby/Rack applications (http://puma.io)
gem 'puma'
# A fast and robust web server and application server for Ruby, Python and Node.js (https://www.phusionpassenger.com/)
gem 'passenger'
# Font-Awesome SASS (https://github.com/FortAwesome/font-awesome-sass)
gem 'font-awesome-sass'
# HTTP should be easy (https://github.com/httprb/http)
gem 'http'
# A simple, comprehensive Ruby gem for parsing user agent strings with the help of BrowserScope's UA database (http://github.com/toolmantim/user_agent_parser)
gem 'user_agent_parser'
# File attachments as attributes for ActiveRecord (https://github.com/thoughtbot/paperclip)
gem 'paperclip'
# A Rails gem for Bootstrap Markdown (http://github.com/dannytatom/rails-bootstrap-markdown)
gem 'rails-bootstrap-markdown'
# Ruby bindings for the Stripe API (https://stripe.com/api)
gem 'stripe'
# Markdown that smells nice (http://github.com/vmg/redcarpet)
gem 'redcarpet'
# Fast syntax highlighting for selected languages. (http://coderay.rubychan.de)
gem 'coderay'
# The simplest way to group temporal data (https://github.com/ankane/groupdate)
gem 'groupdate', github: 'ankane/groupdate'
# Create beautiful JavaScript charts with one line of Ruby (http://chartkick.com)
gem 'chartkick', '~> 2.1.1'
# Simple, efficient background processing for Ruby (http://sidekiq.org)
gem 'sidekiq'
# This json is bundled with Ruby
gem 'json', '~> 2.0', '>= 2.0.2'
# Gives you a country object full of all sorts of useful information. (http://github.com/hexorx/countries)
gem 'countries'
# This ensures that devise will update a last_seen flag on the model whenever you check if a user is authed. (http://github.com/ctide/devise_lastseenable)
gem 'devise_lastseenable'
# ActiveModel validation for email. Including MX lookup and disposable email blacklist (https://github.com/lisinge/valid_email2)
gem 'valid_email2'
# retrieve the sourcecode for a method (http://banisterfiend.wordpress.com)
gem 'method_source'
# Block & throttle abusive requests (http://github.com/kickstarter/rack-attack)
gem 'rack-attack'
# Helpers for the reCAPTCHA API (http://github.com/ambethia/recaptcha)
gem 'recaptcha', require: 'recaptcha/rails'
# A Ruby library for generating and verifying one time passwords (http://github.com/mdp/rotp)
gem 'rotp'
# Eventmachine redis client (https://github.com/mloughran/em-hiredis)
gem 'em-hiredis'
# A Ruby client library for Redis (https://github.com/redis/redis-rb)
gem 'redis'
# Converts various bitcoin denominations in Satoshis and back (http://github.com/snitko/satoshi-unit)
gem 'satoshi-unit'

gem 'pp-adaptive'

gem 'dotenv-rails'

gem 'webpush'

gem 'lograge'

gem 'aws-sdk'

gem 'sidekiq-cron'

gem 'newrelic_rpm'

gem 'vuejs-rails'

gem 'sprockets-rails', github: 'rails/sprockets-rails', branch: 'master'

gem 'sprockets', '~> 4.0.0.beta4'

gem 'babel-transpiler'

gem 'camo'

gem 'autoprefixer-rails'

gem 'pry'

gem 'pry-rails'

gem 'webpacker', github: 'rails/webpacker'

gem 'sentry-raven'

gem 'redis-rails'

gem 'identity_cache'

gem 'cityhash'

gem 'active_model_serializers'

gem 'money'

group :development, :test do
  gem 'rack-mini-profiler'
  # Better error page for Rails and other Rack apps (https://github.com/charliesome/better_errors)
  gem 'better_errors'
  # Security vulnerability scanner for Ruby on Rails. (http://brakemanscanner.org)
  gem 'brakeman'
  # Encode/decode HTML entities (https://github.com/threedaymonk/htmlentities)
  gem 'htmlentities'
  # GeoIP searches a GeoIP database for a given host or IP address, and returns information about the country where the IP address is allocated, and the city, ISP and other information, if you have that database version. (http://github.com/cjheath/geoip)
  gem 'geoip'
  # help to kill N+1 queries and unused eager loading. (http://github.com/flyerhzm/bullet)
  gem 'bullet'
  # Profiles loading speed for rack applications. (http://miniprofiler.com)
  # RSpec for Rails (https://github.com/rspec/rspec-rails)
  gem 'rspec-rails'
  # Capybara aims to simplify the process of integration testing Rack applications, such as Rails, Sinatra or Merb (https://github.com/jnicklas/capybara)
  gem 'capybara'
  # factory_girl_rails provides integration between factory_girl and rails 3 (http://github.com/thoughtbot/factory_girl_rails)
  gem 'factory_girl_rails'
  gem 'ffaker'
  gem 'traceroute'
  gem 'formulaic'
  gem 'rails_best_practices'
  gem 'rubocop'
end`

**Comment by palkan** [comment]
Hm, I cannot find `anycable` there

**Comment by Sexual** [comment]
Yes, I copied the production gemfile. I use `anycable-rails` though. The development gemfil is the same just with anycable-rails.

**Comment by palkan** [comment]
Does this error happens only when you use generator? Or with other commands (e.g. `rails c`, `rails s`) too?

**Comment by Sexual** [comment]
Occurs with `rails c` as well.

**Comment by palkan** [comment]
I see you're using `pry`. Can you try simply `pry` and inside it `require 'anycable'`? And also try to prepend with `bundle exec`.
One more question: is it the full error output? When I'm trying to kinda reproduce it I see:

```
RuntimeError: Unable to add defs to DescriptorPool: Symtab already has a def named 'anycable.ConnectionRequest_MapEntry_headers'
from /Users/palkan/dev/anycable/lib/anycable/rpc/rpc.rb:6:in `finalize_to_pool'
```

Do you have smth like the last line, with `finalize_to_pool`?

**Comment by Sexual** [comment]
```ruby
[1] pry(main)> require 'anycable' 
RuntimeError: Unable to add defs to DescriptorPool: Symtab already has a def named 'anycable.ConnectionRequest_MapEntry_headers'
from /home/vagrant/.rvm/rubies/ruby-2.4.0/lib/ruby/gems/2.4.0/gems/anycable-0.4.4/lib/anycable/rpc/rpc.rb:6:in `finalize_to_pool'
[2] pry(main)> 

```

Same happens with bundle exec

**Comment by palkan** [comment]
oh, you also using vagrant; maybe we can try [vagrant share](https://www.vagrantup.com/docs/share/)? btw, I think, it would be better to use [gitter](https://gitter.im/anycable/Lobby) DMs for a quicker communication

**Comment by Sexual** [comment]
Joined gitter.

**Comment by palkan** [comment]
Backtraces with double-loading: 

```sh
/home/vagrant/.rvm/gems/ruby-2.4.0@global/gems/anycable-0.4.4/lib/anycable/rpc/rpc.rb:8:in `<top (required)>'
/home/vagrant/.rvm/gems/ruby-2.4.0@global/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:293:in `require'
/home/vagrant/.rvm/gems/ruby-2.4.0@global/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:293:in `block in require'
/home/vagrant/.rvm/gems/ruby-2.4.0@global/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:259:in `load_dependency'
/home/vagrant/.rvm/gems/ruby-2.4.0@global/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:293:in `require'
/home/vagrant/.rvm/gems/ruby-2.4.0@global/gems/anycable-0.4.4/lib/anycable/rpc_handler.rb:3:in `<top (required)>'
/home/vagrant/.rvm/gems/ruby-2.4.0@global/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:293:in `require'
/home/vagrant/.rvm/gems/ruby-2.4.0@global/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:293:in `block in require'
/home/vagrant/.rvm/gems/ruby-2.4.0@global/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:259:in `load_dependency'
/home/vagrant/.rvm/gems/ruby-2.4.0@global/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:293:in `require'
/home/vagrant/.rvm/gems/ruby-2.4.0@global/gems/anycable-0.4.4/lib/anycable/server.rb:3:in `<top (required)>'
/home/vagrant/.rvm/gems/ruby-2.4.0@global/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:293:in `require'
/home/vagrant/.rvm/gems/ruby-2.4.0@global/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:293:in `block in require'
/home/vagrant/.rvm/gems/ruby-2.4.0@global/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:259:in `load_dependency'
/home/vagrant/.rvm/gems/ruby-2.4.0@global/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:293:in `require'
/home/vagrant/.rvm/gems/ruby-2.4.0@global/gems/anycable-0.4.4/lib/anycable.rb:4:in `<top (required)>'
/home/vagrant/.rvm/gems/ruby-2.4.0@global/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:293:in `require'
/home/vagrant/.rvm/gems/ruby-2.4.0@global/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:293:in `block in require'
/home/vagrant/.rvm/gems/ruby-2.4.0@global/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:259:in `load_dependency'
/home/vagrant/.rvm/gems/ruby-2.4.0@global/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:293:in `require'
/home/vagrant/.rvm/gems/ruby-2.4.0/gems/anycable-rails-0.4.4/lib/anycable/rails.rb:4:in `<top (required)>'
/home/vagrant/.rvm/gems/ruby-2.4.0@global/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:293:in `require'
/home/vagrant/.rvm/gems/ruby-2.4.0@global/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:293:in `block in require'
/home/vagrant/.rvm/gems/ruby-2.4.0@global/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:259:in `load_dependency'
/home/vagrant/.rvm/gems/ruby-2.4.0@global/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:293:in `require'
/home/vagrant/.rvm/gems/ruby-2.4.0/gems/anycable-rails-0.4.4/lib/anycable-rails.rb:2:in `<top (required)>'
/home/vagrant/.rvm/gems/ruby-2.4.0@global/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:293:in `require'
/home/vagrant/.rvm/gems/ruby-2.4.0@global/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:293:in `block in require'
/home/vagrant/.rvm/gems/ruby-2.4.0@global/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:259:in `load_dependency'
/home/vagrant/.rvm/gems/ruby-2.4.0@global/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:293:in `require'
./bin/anycable:4:in `<main>'
/home/vagrant/.rvm/rubies/ruby-2.4.0/lib/ruby/gems/2.4.0/gems/anycable-0.4.4/lib/anycable/rpc/rpc.rb:8:in `<top (required)>'
/home/vagrant/.rvm/gems/ruby-2.4.0@global/gems/anycable-0.4.4/lib/anycable/rpc/rpc_services.rb:5:in `require_relative'
/home/vagrant/.rvm/gems/ruby-2.4.0@global/gems/anycable-0.4.4/lib/anycable/rpc/rpc_services.rb:5:in `<top
```
