### ISSUE TITLE
RAILS_ENV=production bundle exec anycable not doing anything

### ISSUE THREAD

**Issue by sean-yeoh** [anycable/anycable#111]
### Tell us about your environment
Hi guys, I can't get anycable running on my production server. I'm using linode Ubuntu 20.04 instance if that helps.
The weird thing is `RAILS_ENV=production bundle exec anycable -v` prints out the anycable version but `RAILS_ENV=production bundle exec anycable` is not doing anything. 

**Ruby version:**
ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-linux]

**`anycable` gem version:**
v1.0.1

**`grpc` gem version:**
v1.32.0

### What did you do?
`RAILS_ENV=production bundle exec anycable`

### What did you expect to happen?
It should show that AnyCable gRPC server is running
This works on my local ubuntu 20.04 laptop.
```
Starting AnyCable gRPC server (pid: 77626, workers_num: 30)
AnyCable version: 1.0.1 (proto_version: v1)
gRPC version: 1.32.0
Serving Rails application from ./config/environment.rb
Broadcasting Redis channel: __anycable__
RPC server is starting...
RPC server is listening on 127.0.0.1:50051
```

### What actually happened?
Nothing. Nothing was print out from my console.
![image](https://user-images.githubusercontent.com/18374402/96372599-23e86280-119a-11eb-94df-6de9c08be535.png)

**Comment by palkan** [comment]
Checkout your Rails production logging settings. AnyCable uses Rails logger by default: https://docs.anycable.io/#/v1/rails/getting_started?id=logging

**Comment by sean-yeoh** [comment]
Ahhh, gotcha. It's showing now. Thanks a lot! @palkan 

Closing this issue.
