### ISSUE TITLE
Random Segmentation Fault crash in production

### ISSUE THREAD

**Issue by Michaelvilleneuve** [anycable/anycable#112]
### Tell us about your environment

**AnyCable-Go version: 1.0**

**AnyCable gem version: 1.0.2**

**Ruby version : 2.7.1p83**

### What did you do?

We launched anycable in production

### What did you expect to happen?

No regression or added crash in production

### What actually happened?

```
[BUG] Segmentation fault at 0x0000000000000000
```

We have seen some random deep crashes "Segmentation fault" in production when making http requests from the backend. 
They appeared right after having deployed anycable in production for the first time.

From our investigations, this seems like an occurrence of the following [bug](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=966653#10) caused by the direct and indirect addition of 2 gems from anycable : grpc and google-protobuf. 

![image](https://user-images.githubusercontent.com/4990201/98552785-2c1a5600-229f-11eb-9632-c04182c2c1e0.png)

![image](https://user-images.githubusercontent.com/4990201/98553584-0e012580-22a0-11eb-9bb6-8c492fc283db.png)

Please note that in the image the crash appears indirectly linked to the bearer gem because it wraps all network call.
Also please note that the crash is probably not directly linked to anycable code but rather to the following libs : 
- grpc
- google-protobuf
which version are not set in the gemspec : 
```ruby
spec.add_dependency "grpc", "~> 1.17"
```
A potential solution may be to force using the 1.17 version : 

```ruby
spec.add_dependency "grpc", "1.17"
```

We will try to fork the project and set the version in our project to see if this fixes the crash

**Comment by Michaelvilleneuve** [comment]
Ok I have been unable to fix the dependency to 1.17 since we need support for ruby 2.7.1. I am making some tests on 1.28.0, I'll post some results here

**Comment by palkan** [comment]
> the crash appears indirectly linked to the bearer gem because it wraps all network call

Yeah, looks like that's the reason. Couldn't find the source of this gem. Do you know whether it's available somewhere? (Except from downloading the gem and extracting the contents 🙂).

**Comment by Michaelvilleneuve** [comment]
No unfortunately I don't but as I said the bug is very likely caused by the combination of Grpc et Protobuff and is very similar to a bug referenced here in Gitlab issues https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=966653#10.

We are currently trying to deploy a version without the bearer gem in order to get a proper stacktrace. I'll keep you up to date. 


Also, following my previous comment, the fork we've been deploying with Grpc 1.28.0 also has the same problem.

**Comment by Michaelvilleneuve** [comment]
Hi again, we have removed Bearer gem and it has fixed the problem. It is probably a conflict between indirect gems added by anycable and the bearer gem. 
We have notified Bearer of the problem, they have delivered a fix which we will try soon. In the meantime, I think we can close this. Thanks :)
