### ISSUE TITLE
able to change default healthcheck path?

### ISSUE THREAD

**Issue by jjb** [anycable/anycable#116]
Hi, thanks for this amazing project!

I'm confused about the healthcheck server behavior. it seems like by default there is a healthcheck endpoint at /health on the same port as the websockets server.

when i try to change the path, it doesn't work. when i specify both a new path and port, then it creates another parallel server on that port, with that path.

is this the expected behavior?

is there a way to change the path on the default server? (pretty much a necessity in my deploy environment)

thanks!

![image](https://user-images.githubusercontent.com/6097/106175416-01e57f80-618e-11eb-898a-9449685f4ea3.png)
![image](https://user-images.githubusercontent.com/6097/106175195-bdf27a80-618d-11eb-9022-934f96f95f55.png)
![image](https://user-images.githubusercontent.com/6097/106175209-c0ed6b00-618d-11eb-9bed-8c3475cd4c4c.png)

**Comment by jjb** [comment]
If i add this to my anycable.yml

```yml
  http_health_port: 8080
  http_health_path: '/X'
```

1. the healthcheck _does_ work on that port... does it collide with the actual WS server though? i haven't tested yet.
2. the output still says /health, as shown in screenshots above
3. /health does _not_ work

**Comment by jjb** [comment]
and more mystery, i can't for the life of me figure out which code produces "Handle health connections at" 😅

**Comment by palkan** [comment]
> does it collide with the actual WS server though?

That would prevent anycable-go health server to listen on this port, it should fail, I guess.

If you're trying to mount anycable-go health server at `/X`, then you're command is slightly wrong. You need:

```sh
bundle exec anycable --server-command="anycable-go --health-path='/X'"
```

And then you'll see the right output.

`--http-server-path` is for AnyCable RPC process. Yeah, there are two different health servers)

**Comment by jjb** [comment]
ahh, gotcha. thanks, working now!
