### ISSUE TITLE
localhost vs. 0.0.0.0

### ISSUE THREAD

**Issue by jjb** [anycable/anycable#117]
On my PaaS, aptible, here's what I'm currently using in my Procfile (not production yet)

    anycable: exec bundle exec anycable --server-command="anycable-go --host=0.0.0.0 --health-path='/healthcheck'"

`--host=0.0.0.0` was something that took a while for me to debug,  I wonder if it should be mentioned somewhere in the docs. Maybe this isn't required on Heroku.

**Comment by sponomarev** [comment]
Hey @jjb, AFAIR it's mentioned in the docs explicitly to be configured via `ANYCABLE_HOST` variable.

https://docs.anycable.io/#/v1/deployment/heroku?id=configuring-the-apps
