### ISSUE TITLE
Inconsistency in the releases list on GH vs RubyGems

### ISSUE THREAD

**Issue by mensfeld** [anycable/anycable#128]
Hey there,

My name is Maciej Mensfeld and I run security & quality assessment for OSS libraries using WhiteSource Diffend.io.

While reviewing your recent release of anycable, I noticed that there are releases on RubyGems that are not present on Github. This may be a bit confusing for users (it surely is for me). Just wanted to let you know about this.

Have a nice day.

**Comment by Envek** [comment]
Are you talking about [1.1.0.pre1](https://rubygems.org/gems/anycable/versions/1.1.0.pre1)? I can't see any other recent release that exists in Rubygems but have no corresponding tag on GitHub.

**Comment by mensfeld** [comment]
@Envek you're right. Sorry for the plural in the title and description. Now that you are aware, closing :)

**Comment by Envek** [comment]
@palkan don't you want to create tag for that release?

**Comment by palkan** [comment]
> don't you want to create tag for that release?

Not really: `pre` releases are not meant to be used by the end users; they're mostly for internal testing/CI.

**Comment by mensfeld** [comment]
The reason why I raised this, is that some of the ATO attacks target registries instead of GH, creating a mismatch in releases because they appear in registry and do not in GH. While I understand the pre-release policy not hitting the registry I would ask you to reconsider based on my explanation. Thank you :pray:
