### ISSUE TITLE
AnyCable 1.1.0 suggests anycable-grpc

### ISSUE THREAD

**Issue by ryansch** [anycable/anycable#131]
### Tell us about your environment

**Ruby version:**
2.7.3
**`anycable` gem version:**
1.1.0
**`grpc` gem version:**
1.38.0
### What did you do?
Upgraded to AnyCable 1.1.0 from 1.0.x.
### What did you expect to happen?
I expected to be able to start anycable.
### What actually happened?
I was unable to start anycable and I received an error suggesting I install `anycable-grpc` which doesn't exist.

The particular error comes from here: https://github.com/anycable/anycable/blob/13ccb312eea94d56474e57b70eff74197cb8c195/lib/anycable/cli.rb#L255

I believe the error should be updated to suggest the user installs the `grpc` gem.

**Comment by palkan** [comment]
Thanks for catching this!
