### ISSUE TITLE
I need to integrate rails, actioncable, nginx, redis

### ISSUE THREAD

**Issue by mices** [anycable/anycable#134]
Should I use this gem to integrate rails, actioncable, nginx, redis I'm already running the redis server in addition to a node server on two different ports My nginx is the passenger nginx module

**Comment by palkan** [comment]
You need this gem to integrate Rails, Action Cable and AnyCable WebSocket server (such as [anycable-go](https://github.com/anycable/anycable-go)).

If you're using a different WebSocket server (some "node server"), then "no, you don't need it".

Please, check the [AnyCable documentation](https://docs.anycable.io).
