### ISSUE TITLE
Unable to authenticate users in AWS EKS with anycable 0.6.5

### ISSUE THREAD

**Issue by sdhull** [anycable/anycable#142]
### Tell us about your environment

**Ruby version:** 2.4.9

**`anycable` gem version:** 0.6.5

**`grpc` gem version:** 1.41.1

**`anycable-go` version:** 0.6.5

Note: We're working on upgrading Rails so we can upgrade Ruby, but this is an ongoing effort that will take some time.

### What did you do?
Deployed to Kubernetes.

In our `ApplicationCable::Connection` class, we find the user like this (using devise):

```ruby
    def find_current_user
      env["rack.session"] = ActionDispatch::Cookies::EncryptedCookieJar.new(cookies)[:_kjb_session]

      Warden::SessionSerializer.new(env).fetch(:user) || reject_unauthorized_connection
    end
```

### What did you expect to happen?
To find the user so the connection could authenticate. Works fine running everything locally.

### What actually happened?
Unable to authenticate users, we are running both `anycable-go` and `anycable` with `--debug` but don't see cookies in the output. The RPC server shows logs like:

```
[AnyCable sid=NDwTmR1yKA3SHkxiaEJwo0] An unauthorized connection attempt was rejected
deadline is 1969-12-31 23:59:59 +0000; (now=2022-02-07 20:05:00 +0000)
schedule another job
```

Websocket request in Chrome devtools shows headers being sent. Inspecting packets on nodes in kubernetes _seems_ to show something that looks like cookies arriving at the RPC server (I can see `_kjb_session` for example), but not sure if it's in a valid format.

Not sure what our next debug step should be. Any help would be greatly appreciated!

**Comment by palkan** [comment]
> Not sure what our next debug step should be. Any help would be greatly appreciated!

Can you reproduce it in a dev env?
One thing to check is a secret key base. Make sure it's the same for all pods. If it's not, encrypted cookies silently return an empty Hash after decryption, no warnings printed.

See https://github.com/rails/rails/blob/0cad778c2605a5204a05a9f1dbd3344e39f248d8/actionpack/lib/action_dispatch/middleware/cookies.rb#L536-L540

You can try patching this method to show a warning.

**Comment by sdhull** [comment]
Thank you so much for the prompt reply! ❤️ 

> Can you reproduce it in a dev env?

No, we haven't been able to repro in local environments. 

> One thing to check is a secret key base

Will double-check this asap. I _assumed_ they'd be the same because of how we set them up, but this is a great thing to sanity check, thank you!!

**Comment by invsblduck** [comment]
Thank you, @palkan. I can confirm `SECRET_KEY_BASE` is identical in all pods. This tip is also mentioned in the Troubleshooting guide [here](https://github.com/anycable/docs.anycable.io/blob/master/docs/troubleshooting.md#my-websocket-connection-fails-with-auth-failed-error) (item no. 2). :+1: 

Upon inspecting gRPC traffic in the anycable pod (ie., the container with `bundle exec anycable --rpc-host=0.0.0.0:50051 --debug`), I notice that 75% of the incoming headers are "unknown" to Wireshark... This may only be the effect of Wireshark not interpreting the format correctly, but I wonder if the payloads on the wire are in fact valid:

![image](https://user-images.githubusercontent.com/1899464/153059631-17cd451c-07dd-4d76-933a-7d2e6b893e52.png)

^ I do see the cookies in the `DATA` section.

In the blog post [gRPC - raw requests](https://bkubiak.github.io/grpc-raw-requests/) (unrelated to AnyCable), I see his Wireshark capture shows more headers in the screenshot image. :thinking:

**Comment by invsblduck** [comment]
@palkan We discovered the EKS environment is using Redis for sessions. :wink: Then we also discovered the 'missing' documentation accidentally: [v.0.6.x of the Authentication page](https://docs.anycable.io/v06/ruby/authentication)&#8212;which isn't actually missing, of course&#8212;but mentions _Redis_ and links to an example (in [Issue 95 of `anycable-rails`](https://github.com/anycable/anycable-rails/issues/95#issuecomment-502458973)). The newer [1.2 Authentication doc](https://docs.anycable.io/rails/authentication) alludes to the concept more abstractly; finding the old page is what triggered the "aha" :bulb::thinking: moment about our mistake.

Thank you for your amazing Ruby contributions and all that you do!
