### ISSUE TITLE
Auth Failed - 743: unexpected token at ''

### ISSUE THREAD

**Issue by woodcrust** [anycable/anycable#16]
Добрый день
Подскажите, получаю ошибку
anycable rpc :
```
deadline is 1970-01-01 02:59:59 +0300; (now=2017-07-18 13:36:59 +0300)
schedule another job
RPC Connect: #<Anycable::ConnectionRequest:0x007f2b8cb91a18>
743: unexpected token at ''
```
и
anycable-go :
```
Auth 
Auth Failed
```

сразу после подключения любым из нижеперечисленных способов
```
node
ws = new WebSocket('ws://domain:8080/cable');
JS
socket = new WebSocket('ws://domain:8080/cable');
swift
let socket = WebSocket(url: URL(string: "ws://domain:8080/cable")!, protocols: ["actioncable-v1-json", "actioncable-unsupported"])
```

объясните пожалуйста в чем суть проблемы, что я пропускаю ?

**Comment by palkan** [comment]
Добрый день,

Судя по всему где-то идёт попытка распарсить пустую строку как JSON.

А что в методе `#connect` у ApplicationCable::Connection?

**Comment by woodcrust** [comment]
Спасибо огромное так и есть, на ios версии я отправляю в headers cookie ...
