### ISSUE TITLE
Flags for WebSocket frame sizes

### ISSUE THREAD

**Issue by cezartiv** [anycable/anycable#176]
I am not very versed in the websockets protocol, so it took quite a bit of time to understand why a bug was happening. There is a client written in c# that subscribes to our rails server via websockets. Previously ws was implemented via ActionCable, and everything worked as expected. While upgrading to AnyCable I observed that packets where being sliced into pieces of 1024 characters, which prevented the client to receive them properly. It was a mystery for quite a while why the bug happened with AnyCable and not with ActionCable, and why it was happening with this c# client, while the browser recieved full messages as expected. Eventually I screened the traffic in Wireshark, and observed the following behavior:

- In AnyCable if a message had more than 1024 bytes, it was sent first in a *WebSocket Text* frame, of size 1096(of which 1024 was the payload), then in several *WebSocket Continuation* frames, the last of which contained the FIN bit.

- In ActionCable the message was sent within a single *WebSocket Text* frame, which also contained the FIN bit.

Probably the implementation of the C# client is also at fault here, since Continuation Frames are a full part of the spec and should therefore be properly implemented. But we don't currently have access to the client code, and thus the migration to AnyCable breaks a currently working flow.

Thus a question: is there any flag or setting to increase the size of the AnyCable frames, so that the entire message would be sent within a single frame?

**Ruby version:3.0.4**

**`anycable` gem version:1.2.5**

**`grpc` gem version:1.37**

**Comment by palkan** [comment]
Yes, there is the `--write_buffer_size` flag (which defaults to 1024), which you can adjust to your needs. Increasing it should help. (Please, let me know if doesn't)

**Comment by cezartiv** [comment]
Thank you very much! Indeed, this fixed the issue.
