### ISSUE TITLE
Confusing `-r` description

### ISSUE THREAD

**Issue by x-yuri** [anycable/anycable#184]
### Tell us about your environment

**Ruby version:** (the report is based on the source code)

**`anycable` gem version:** 1.2.5

**`grpc` gem version:** (the report is based on the source code)

### What did you do?
ran `anycable --help`

### What did you expect to happen?
the description to not be confusing

### What actually happened?
It said:

> -r, --require=path                Location of application file to require, default: "config/environment.rb"

But first there are 2 candidates:

https://github.com/anycable/anycable/blob/726f7b2cbdea8bac6c6cc745d962985a046b82d1/lib/anycable/cli.rb#L14-L17

Second, the path should start with `./`:

https://github.com/anycable/anycable/blob/726f7b2cbdea8bac6c6cc745d962985a046b82d1/lib/anycable/cli.rb#L159

**Comment by palkan** [comment]
Thanks for reporting! Fixed in master
