### ISSUE TITLE
Server Crash in native go code.

### ISSUE THREAD

**Issue by adamcooper** [anycable/anycable#190]
### Tell us about your environment

**Ruby version:** 3.1.2

**`anycable` gem version:** 1.2.5

**`grpc` gem version:** 1.52.0

### What did you do?

Running the anycable server in heroku environment with two dynos

### What did you expect to happen?

Not crash and continue running.

### What actually happened?

One of the dynos crashes with the following output:

```
"/app/vendor/bundle/ruby/3.1.0/gems/anycable-core-1.2.5/lib/anycable/cli.rb:201:in `block in run_custom_server_command!': Server command exit unexpectedly (Interrupt)",
  "#<Thread:0x00007f09c7292bd8 /app/vendor/bundle/ruby/3.1.0/gems/anycable-core-1.2.5/lib/anycable/cli.rb:195 run> terminated with exception (report_on_exception is true):",

  "/go/src/github.com/anycable/anycable-go/node/session.go:77 +0x385",
  "created by github.com/anycable/anycable-go/node.NewSession",
  "/go/src/github.com/anycable/anycable-go/node/session.go:124 +0xe7",
  "github.com/anycable/anycable-go/node.(*Session).SendMessages(0xc00097c900)",
  "goroutine 1003225 [chan receive, 21 minutes]:",
  null,
  "/go/src/github.com/anycable/anycable-go/node/session.go:77 +0x385",
  "created by github.com/anycable/anycable-go/node.NewSession",
  "/go/src/github.com/anycable/anycable-go/node/session.go:124 +0xe7",
  "github.com/anycable/anycable-go/node.(*Session).SendMessages(0xc0004d3080)",
  "goroutine 1468695 [chan receive, 5 minutes]:",
  null,
  "/go/src/github.com/anycable/anycable-go/node/session.go:77 +0x385",
  "created by github.com/anycable/anycable-go/node.NewSession",
  "/go/src/github.com/anycable/anycable-go/node/session.go:124 +0xe7",
  "github.com/anycable/anycable-go/node.(*Session).SendMessages(0xc0012cd080)",
  "goroutine 1541201 [chan receive, 1 minutes]:",
  null,
  "/go/src/github.com/anycable/anycable-go/node/session.go:92 +0x49",
  "created by github.com/anycable/anycable-go/node.(*Session).Serve",
  "/go/src/github.com/anycable/anycable-go/node/session.go:96 +0x58",
  "github.com/anycable/anycable-go/node.(*Session).Serve.func1(0xc000a1ce10, 0xc000879bc0)",
  "/go/src/github.com/anycable/anycable-go/ws/connection.go:57",
  "github.com/anycable/anycable-go/ws.Connection.Read(...)",
```

[More log error details available as a gist.](https://gist.github.com/adamcooper/f09b578096aaade6df5b72704032c136)

**Comment by palkan** [comment]
Unfortunately, the panic log isn't complete (first lines indicated the reason are missing).
However, I see that you're running v1.1.0, which is rather old and a few of deadlock/race condition bugs have been fixed since then. So, I'd recommend upgrading to the latest release (v1.2.3) first. If that won't help, we need to figure out how to get a full error log back from anycable-go.

**Comment by palkan** [comment]
Hey @adamcooper! Any updates here?

**Comment by adamcooper** [comment]
@palkan - Thanks for the follow up and quick response.  

After updating to 1.2.3 we've only seen one crash a month.  Previously we had seen 6 crashes in the previous 6 weeks.

I'll close this for now and re-open if I see it start happening more regularly or have a complete stacktrace.
