### ISSUE TITLE
Docs issue - missing "g" in anycable:download instructions

### ISSUE THREAD

**Issue by shoffing** [anycable/anycable#205]
![image](https://github.com/anycable/anycable/assets/2903742/3c8a85d7-3bdd-4ade-aff1-69dc1032946e)

There should be a `g` in there, so it's 

```bundle exec rails g anycable:download```

Link to docs page: https://docs.anycable.io/rails/getting_started?id=server-installation

**Comment by palkan** [comment]
Thanks! Fixed by https://github.com/anycable/anycable-rails/commit/a0657325fff0a56f4e4cb2fd7667e2871217bf39
