### ISSUE TITLE
ArgumentError: unknown keywords: "host", "port", "password"

### ISSUE THREAD

**Issue by phlegx** [anycable/anycable#215]
### Tell us about your environment

**Ruby version:** 3.2.2

**`redis` gem version:** 5.0.7

**`redis-client` gem version:** 0.16.0 (runtime dependency of redis gem)

**`anycable` gem version:** 1.4.1

**`anycable-rails` gem version:** 1.4.1

**`grpc` gem version:** 1.57.0

### What did you do?

I set `redis_sentinels` in `config/anycable.yml` like this (array is created dynamically):

```yaml
development:
  redis_sentinels:
    - { host: '0myho.st', port: 1234, password: 'xyz' }
    - { host: '1myho.st', port: 1234, password: 'xyz' }
```

### What did you expect to happen?

AnyCable work with sentinels.

https://github.com/redis/redis-rb#sentinel-support

### What actually happened?

Code line 174 with `transform_keys!` does not seam to work. Keys remain the same as before. https://github.com/anycable/anycable/blob/f22568b59aca169621495f133fbe9f161d4e47a7/lib/anycable/config.rb#L174

```log
ArgumentError: unknown keywords: "host", "port", "password"
/bundle/ruby/3.2.0/gems/redis-client-0.16.0/lib/redis_client/config.rb:21:in `initialize'
/bundle/ruby/3.2.0/gems/redis-client-0.16.0/lib/redis_client/config.rb:176:in `initialize'
/bundle/ruby/3.2.0/gems/redis-client-0.16.0/lib/redis_client/sentinel_config.rb:111:in `new'
/bundle/ruby/3.2.0/gems/redis-client-0.16.0/lib/redis_client/sentinel_config.rb:111:in `block in sentinels_to_configs'
/bundle/ruby/3.2.0/gems/redis-client-0.16.0/lib/redis_client/sentinel_config.rb:106:in `map'
/bundle/ruby/3.2.0/gems/redis-client-0.16.0/lib/redis_client/sentinel_config.rb:106:in `sentinels_to_configs'
/bundle/ruby/3.2.0/gems/redis-client-0.16.0/lib/redis_client/sentinel_config.rb:53:in `initialize'
/bundle/ruby/3.2.0/gems/redis-client-0.16.0/lib/redis_client.rb:148:in `new'
/bundle/ruby/3.2.0/gems/redis-client-0.16.0/lib/redis_client.rb:148:in `sentinel'
/bundle/ruby/3.2.0/gems/redis-5.0.7/lib/redis/client.rb:27:in `sentinel'
/bundle/ruby/3.2.0/gems/redis-5.0.7/lib/redis.rb:155:in `initialize_client'
/bundle/ruby/3.2.0/gems/redis-5.0.7/lib/redis.rb:73:in `initialize'
/bundle/ruby/3.2.0/gems/anycable-core-1.4.1/lib/anycable/broadcast_adapters/redis.rb:34:in `new'
```

Instead `sentinel.symbolize_keys` does it correctly (but it is a Rails method). 

Adding a `to_h` (Ruby method) solves it: `sentinel.to_h.transform_keys!(&:to_sym)`

**Comment by palkan** [comment]
Thanks for the report. It turned out that in Rails context we deal with ActiveSupport::HashWithIndifferentAccess, and since it uses String keys internally, calling `transform_keys!(&:to_sym)` has no effect.

Fixed and released in 1.4.2.
