### ISSUE TITLE
Fails w/ ruby 3.3.0

### ISSUE THREAD

**Issue by brandall10** [anycable/anycable#223]
### Tell us about your environment

**Ruby version: 3.3.0** 

**`anycable` gem version: 4.1.3 **

**`grpc` gem version: 1.60.0-arm64-darwin**

### What did you do?

Tried to invoke anycable w/ `bundle exec anycable`

### What did you expect to happen?

For it to properly launch per documentation.

### What actually happened?

The error at the bottom of the stack is: .rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/anyway_config-2.6.1/lib/.rbnext/3.4/anyway/tracing.rb:32: anonymous keyword rest parameter is also used within block

Can confirm locking anyway_config to 2.5.4 per mention at bottom of issue reported there fixes it - https://github.com/palkan/anyway_config/issues/144

**Comment by palkan** [comment]
Fixed in anyway_config (`>= 2.6.2`).

The actual cause was in the Ruby itself: https://bugs.ruby-lang.org/issues/20090
