### ISSUE TITLE
Does AnyCable work on AWS ECS despite shoddy HTTP2 support from ALBs?

### ISSUE THREAD

**Issue by dimroc** [anycable/anycable#23]
Hi there,
I'm hoping to use anycable on Amazon ECS, but recently found out that grpc isn't well supported in ECS and their Application Load Balancers (ALBs) due to a sketchy HTTP2 implementation. Without proper grpc support, is it safe to assume that anycable can't be hosted on ECS? 

Reference:
https://groups.google.com/forum/#!topic/grpc-io/8s7UHY_Q1po

Thanks!

**Comment by palkan** [comment]
Hi!

As it is stated in google groups topic, it's not possible (or hardly possible) to use built-in ECS load balancers for gRPC traffic.

But that does not mean that you cannot use Anycable with ECS:

- You can use your own load balancer as a separate service (see [official guide](https://grpc.io/blog/loadbalancing) on load balancing)

- You can run RPC server and WebSocket server within one container and thus use ALB for HTTP WebSocket traffic only (that's how we run Anycable on [Heroku](https://github.com/anycable/anycable/wiki/%5BEXPERIMENTAL%5D-Heroku-Deployment)). Not so good, but works.

**Comment by dimroc** [comment]
Thanks a lot @palkan. I'll look into option 2. Before reading your response, I had decided to make the switch to GKE (https://cloud.google.com/container-engine/) since kubernetes supports gRPC and I have need for it outside of anycable.

**Comment by dimroc** [comment]
Btw, regarding approach 2, multicontainer pods are a perfect fit:

https://kubernetes-v1-4.github.io/docs/user-guide/pods/multi-container/#the-spec-schema
