### ISSUE TITLE
Rack::VERSION is removed from Rack 3.1.0 to Rack 3.1.2

### ISSUE THREAD

**Issue by jonh-favo** [anycable/anycable#234]
Since Rack::VERSION has been removed from Rack 3.1.0, anycable won't start anymore. 

It just fails with the message `uninitialized constant Rack::VERSION`

According to the release notes for Rack you should use Rack::RELEASE instead.

**Comment by jonh-favo** [comment]
It seems like they added the Rack::VERSION again, so it will be included in an upcoming Rack 3.1.3 release, so that means that Anycable won't support Rack 3.1.0 -> Rack 3.1.2, but should be good to go when this new update has been released. 

https://github.com/rack/rack/pull/2199

**Comment by Earlopain** [comment]
`Rack::VERSION` got semantically changed. Previously it contained something to put in `rack.version` (which got deprecated as well)

3.0 changelog:
> `rack.multithread`/`rack.multiprocess`/`rack.run_once`/`rack.version` are no longer required environment keys.

`Rack::VERSION` will be reintroduced in 3.2 to contain the actual version of the gem.

It seems fine to only add this to the env if `RACK::RELEASE >= 3.0`: https://github.com/anycable/anycable/blob/84b464b5ae1218b220d83c51d74d1906cbb0413a/lib/anycable/socket.rb#L166

**Comment by Earlopain** [comment]
I'll work on a PR for this
