### ISSUE TITLE
Sinatra/Non-rails

### ISSUE THREAD

**Issue by pchaganti** [anycable/anycable#3]
Can this be used with Sinatra or any non-rails frameworks? 

thanks

**Comment by palkan** [comment]
Not yet. But I'm working on it. This is the feature of a high priority.

**Comment by pchaganti** [comment]
awesome :) thanks!

**Comment by palkan** [comment]
Check out https://github.com/palkan/litecable.

And this [sinatra example](https://github.com/palkan/litecable/tree/master/examples/sinatra).
