### ISSUE TITLE
Connections tracking

### ISSUE THREAD

**Issue by kurbaitis** [anycable/anycable#31]
Hello everyone,

First of all, the product which you are creating looks amazing.

I'm working on a quite sophisticated solution when it comes to websockets. My current feature needs to track users as online/offline. For that I use ActionCable appearance channel where I have `def subscribed` and `def unsubscribed` and respectively flag an user online or offline.

The problem appears with multiple browser tabs or windows. With this you get multiple subscriptions and if you close one, you don't need to flag the user as offline.

To avoid these conflicts I need to know what are current subscriptions/connections present at that point.
With ActionCable (and without AnyCable) you can do `ActionCable.server.connections` which is returning accumulated connections and you still can't trust it but still it returns at least something. With AnyCable the result is always an empty array.

My question would be, is there any chance I could get the global subscriptions/connections data from anywhere in your product?

**Comment by palkan** [comment]
What you're talking about is a _Presence_ feature. It's very common feature for real-time frameworks, but Action Cable doesn't provide it out of the box.

There are no plans to build something similar for Anycable, 'cause Anycable is supposed to be more like a proxy server. But that doesn't mean we're not thinking about the feature)

I've already proposed a simple implementation [here](https://github.com/anycable/anycable-rails/issues/12#issuecomment-319362658), which looks pretty similar to what [Phoenix](https://hexdocs.pm/phoenix/Phoenix.Presence.html) has.

**Comment by kurbaitis** [comment]
Thanks @palkan, I think I'll go with redis based counter for existing subscriptions tracking and see where it leads me.
