### ISSUE TITLE
Benchmarks for nodejs and other languages?

### ISSUE THREAD

**Issue by rmacklin** [anycable/anycable#33]
Hi,

This project seems really awesome!

For I while I was interested in ActionCable, but I knew that it would have pretty serious performance issues in production. So I haven't used it in a production site. I've worked on a production site that uses [Faye](https://faye.jcoglan.com/) for node (which is considerably faster than Faye for Ruby).

After seeing the benchmarks from [the AnyCable blog post](https://evilmartians.com/chronicles/anycable-actioncable-on-steroids#benchmarks-anycable), I was very impressed by the performance gains you've made while sticking to the ActionCable API. However, the graphs made me curious about comparisons to other languages than just Go and Erlang. For instance, it'd be cool to use the graph to ballpark how much faster switching from node Faye to AnyCable-Go or ErlyCable might be. And also it'd just be interesting to see a few of the other popular languages in the graph. If this isn't something you're interested in, is there anything you can provide for how someone else might run the same benchmarks for different platforms?

Thanks!

**Comment by palkan** [comment]
Hi, @rmacklin!

Thanks for the feedback!

Additional benchmarks could be found here https://github.com/anycable/anycable/blob/master/benchmarks/2017-02-12.md (and [some instructions](https://github.com/anycable/anycable/tree/master/benchmarks) on how to run them).

I didn't include results for NodeJS Faye though. As I remember, it showed not so good performance comparing to uWS JS, which is pretty cool, btw, and almost identical to Golang implementations.

> And also it'd just be interesting to see a few of the other popular languages in the graph

Any specific suggestions?

**Comment by rmacklin** [comment]
Wow, I feel pretty stupid for missing the benchmarks directory in the repo! Sorry about that, and thanks for responding kindly. But in case anyone else is as blind as me, it might be helpful to mention the benchmarks in the readme, and/or update the graphs in the blog post & slide deck to include these additional stats.

> I didn't include results for NodeJS Faye though. As I remember, it showed not so good performance comparing to uWS JS

Thanks for sharing, that's good to know.

> uWS JS, which is pretty cool, btw, and almost identical to Golang implementations.

Also interesting...would this mean it might not be too difficult to implement an "anycable-uws" based on the anycable-go implementation? Is that anything you looked into at all? If it's not already clear, websockets are not at all my domain of expertise, but helping to build an anycable server that runs on node might be a good way to learn...

> Any specific suggestions?

I guess other than node, the one that came to mind was python/django channels.

**Comment by palkan** [comment]
> python/django channels.

Oh, I've tried django channels. Either I don't know how to cook them properly or they're not ready yet–that was the worst performance I've ever seen.

I've been experimenting with AnyCable for Python (i.e. AnyCable server + Python RPC = ActionCable for Python). Just out of curiosity. I'm not proficient in Python web development.

> would this mean it might not be too difficult to implement an "anycable-uws" based on the anycable-go implementation

There is a [wiki](https://github.com/anycable/anycable/wiki/Writing-Custom-AnyCable-Server) article explaining how to write your own WebSocket server for AnyCable. It should not be difficult at all.

But I think, if we need one more implementation than it's better to consider C++ uWS–that would make more sense from the performance point of view.

**Comment by rmacklin** [comment]
Fair enough. I was mainly interested in a nodejs version for somewhat selfish reasons (the aforementioned project doesn't use a container-based deployment infrastructure yet, so currently only ruby and node services can be deployed easily).

Anyway, thanks for your answers! I'll close this issue
