### ISSUE TITLE
Envoy не балансирует

### ISSUE THREAD

**Issue by rus-max** [anycable/anycable#49]
Привет, @palkan!

Procfile:
rpc1: ANYCABLE_RPC_HOST=0.0.0.0:50060 bundle exec ./bin/anycable
rpc2: ANYCABLE_RPC_HOST=0.0.0.0:50061 bundle exec ./bin/anycable
anycable-go: bundle exec ./bin/anycable-go --host=0.0.0.0 --port=3334

Envoy запустил, как в примере.

При коннекте на ws выдаёт ошибку:
context=ws Websocket session initialization failed: rpc error: code = Unavailable desc = upstream connect error or disconnect/reset before headers

**Comment by palkan** [comment]
Привет!

Ошибка говорит о том, что Envoy не может достучаться до RPC. Envoy запущен в докере? Хост-машина из контейнера точно доступна по `"docker.for.mac.localhost"`? Можно попробовать сделать `docker exec` в контейнер и посмотреть, доступен ли хост из контейнера в принципе

**Comment by rus-max** [comment]
Envoy запущен в докере, остальное запущено на той же машине (не в докере).

Указал в хостах envoy.yaml
socket_address: {}

**Comment by rus-max** [comment]
Может envoy не может достучаться наружу к rpc?

**Comment by palkan** [comment]
> Может envoy не может достучаться наружу к rpc?

Скорее всего.

> socket_address: {address: 0.0.0.0, port_value: 50060}

`0.0.0.0` точно не подходит, это ж внутри контейнера адрес; нужен адрес хост-машины (зависит от ОС и способа работы с докером)

**Comment by rus-max** [comment]
Заменил address на docker.for.linux.host.internal

Ошибка поменялась
context=ws Websocket session initialization failed: rpc error: code = Unavailable desc = no healthy upstream

**Comment by palkan** [comment]
Closed as stale
