### ISSUE TITLE
Receiving cryptic error when actioncable pings server

### ISSUE THREAD

**Issue by RailsCod3rFuture** [anycable/anycable#56]
For some reason, I get  ActionController::RoutingError (No route matches [GET] "/("):. Am I running the server incorrectly?

```
Use Ctrl-C to stop
Started GET "/(?-mix:ws:\/\/*)%20(?-mix:wss:\/\/*)" for 127.0.0.1 at 2018-10-29 23:44:29 -0400
   (0.0ms)  SELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC
```

**Comment by palkan** [comment]
Which Action Cable do you use and how do you configure the WebSocket URL? Looks like you passed a regexp as an url

**Comment by RailsCod3rFuture** [comment]
After removing the reference to ActionCable in the route file, the error went away.
