### ISSUE TITLE
Windows 10 Compatibility?

### ISSUE THREAD

**Issue by RailsCod3rFuture** [anycable/anycable#57]
I tried to use **rails g anycable:install** and **./bin/anycable** commands. But, they don't seem to be available. I'm currently running **Rails 5.2.0** & **Ruby 2.4.4 x64**. The gem **anycable** itself is version **0.5.5**

**Comment by palkan** [comment]
> But, they don't seem to be available. 

What do you mean? What is the output?

**Comment by RailsCod3rFuture** [comment]
I see that it installed while the gem was installing (didn't need to use the generator). Is this command unique to your environment variable:
```
 RAILS_ENV=production ./bin/anycable
'RAILS_ENV' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by RailsCod3rFuture** [comment]
After using rails generate anycable, they installed.

```
C:\Users\RC\RubymineProjects\ChatApp>rails generate anycable
   identical  bin/anycable
       chmod  bin/anycable
   identical  config/anycable.yml

```
