### ISSUE TITLE
v 0.4.0 - not work

### ISSUE THREAD

**Issue by woodcrust** [anycable/anycable#6]
v 0.4.0 - not work

`RPC Error: rpc error: code = 2 desc = no reason given
2017/01/23 19:56:14 http: panic serving 127.0.0.1:54399: runtime error: invalid memory address or nil pointer dereference
goroutine 54 [running]:
net/http.(*conn).serve.func1(0xc420246000)
	/usr/local/go1.8beta2/src/net/http/server.go:1709 +0xd0
panic(0x140a8a0, 0x1696bd0)
	/usr/local/go1.8beta2/src/runtime/panic.go:489 +0x2cf
main.serveWs(0x16721e0, 0xc42024e000, 0xc4201e8100)
	/Users/nerzh/gopath/src/github.com/anycable/anycable-go/server.go:141 +0x1e3
net/http.HandlerFunc.ServeHTTP(0x149f260, 0x16721e0, 0xc42024e000, 0xc4201e8100)
	/usr/local/go1.8beta2/src/net/http/server.go:1930 +0x44
net/http.(*ServeMux).ServeHTTP(0x16a4a00, 0x16721e0, 0xc42024e000, 0xc4201e8100)
	/usr/local/go1.8beta2/src/net/http/server.go:2226 +0x130
net/http.serverHandler.ServeHTTP(0xc4201684d0, 0x16721e0, 0xc42024e000, 0xc4201e8100)
	/usr/local/go1.8beta2/src/net/http/server.go:2556 +0x92
net/http.(*conn).serve(0xc420246000, 0x1672a20, 0xc4201c02c0)
	/usr/local/go1.8beta2/src/net/http/server.go:1813 +0x612
created by net/http.(*Server).Serve
	/usr/local/go1.8beta2/src/net/http/server.go:2656 +0x2ce

2017/01/23 19:58:07 transport: http2Client.notifyError got notified that the client transport was broken EOF.`

**Comment by palkan** [comment]
Version 0.4.0 has breaking changes (see [Changelog](https://github.com/anycable/anycable/blob/master/CHANGELOG.md#040)).

Use the latest version of `anycable-go` (as for now, 0.3.0), replace `anycable` gem with `anycable-rails` and re-generate RPC server script (`rails g anycable`).

**Comment by woodcrust** [comment]
solved )
