### ISSUE TITLE
Running bundle exec anycable as background process

### ISSUE THREAD

**Issue by johan--** [anycable/anycable#74]
I've moved to anycable after experiencing some issues with actioncable, and it works quite well.

The only remaining issue is the running of 'bundle exec anycable' in the background, any ideas on how to achieve this?  btw - anycable-go works fine with nohup

thanks

**Comment by johan--** [comment]
This is working:

First, set the RAILS_ENV, and then run bundle exec with nohup:

- export RAILS_ENV=production
- nohup bundle exec anycable > log/anycable.log 2>&1 &

**Comment by Envek** [comment]
You can use `anycabled` (it's not yet released as a gem, but you can use it from master branch). See https://github.com/anycable/anycable/pull/69

**Comment by Envek** [comment]
But I strongly advise not to put it in the background but to use process managers or system services instead.

Take a look at [overmind](https://github.com/DarthSim/overmind) or docker-compose for development or [write systemd unit](https://github.com/anycable/anycable-go/issues/51) for staging/production. Also, you can use [monit](https://mmonit.com/monit/).
