### ISSUE TITLE
Ability to broadcast back from channel class synchronously to a received message

### ISSUE THREAD

**Issue by garlou** [anycable/anycable#78]
Hi guys. First of all let me thank you for the excellent job you guys have done here.

I'm having a hard time figuring out this: can we broadcast back directly from a Channel class without using a background job?

Right now I'm trying this use case:

```ruby
class ConversationChannel < ApplicationCable::Channel
  def subscribed
    stop_all_streams
    stream_from(conversation_channel)
    stream_for(conversation_channel)
  end

  def receive(data); end

  def unsubscribed; end

  def send_message(data)
    message = create_message_service(data).call

    # This broadcast only goes through if sent asynchronously on a background job
    ActionCable.server.broadcast(conversation_channel, { data: message })
  end

  private

  def conversation
    current_user.conversation
  end

  def conversation_channel
    "conversation/#{conversation.id}"
  end
end
```

Should this work with Anycable?

### Tell us about your environment

**Ruby version:** 2.5.3

**`anycable` gem version:** 0.6.0

**`grpc` gem version:** 1.17.0

**Comment by palkan** [comment]
Hi @garlou!

> First of all let me thank you for the excellent job you guys have done here.

Thanks!

> Should this work with Anycable?

Yeah, it should.

It's likely one of the following:
- Action Cable adapter is not set to `any_cable` for RPC server
- AnyCable redis channel (set via `ANYCABLE_REDIS_CHANNEL` or in `anycable.yml`) in RPC channel doesn't match the one you use in other instances.

Could you add the following lines to your channel code (before `ActionCable.server.broadcast`) to add some debug information:

```ruby
# Check the broadcast adapter
p ActionCable.server.pubsub
# Check the Redis channel
p AnyCable.broadcast_adapter.channel
```

**Comment by garlou** [comment]
Thanks for the quick answer @palkan .
Here is the output:
```#<ActionCable::SubscriptionAdapter::AnyCable:0x000000000b8145d8>
"__anycable__"````

**Comment by garlou** [comment]
Finally! Got it thanks to you. I was missing the `--redis-channel` flag when starting the gRPC server. 
Thanks
