### ISSUE TITLE
Heroku deployment

### ISSUE THREAD

**Issue by cskaandorp** [anycable/anycable#83]
### Tell us about your environment

**Ruby version:**
2.4

**`anycable` gem version:**
0.6.2

**`grpc` gem version:**
1.17

### What did you do?
Tried the Heroku recipe

### What did you expect to happen?
Beautiful things

### What actually happened?
Nothing

Hi, 

I just have a question and I hope this is the right place to answer it. I am currently working on an app that will serve a specific amount of users( 1000 max) which I'd like to deploy on Heroku.
I have tried to follow your Heroku recipe (https://docs.anycable.io/#/heroku) but I have failed to get it to work. The truth is I'm a bit over my head and don't completely understand what I am doing. The overall idea is clear, but when it comes to debugging why things don't function properly I am nowhere.

That being said: do you think that I really need anycable for this amount of users on Heroku? Maybe a beefed-up standard dyno is enough? I would appreciate your take on this.

Thanks in advance

Cspr

**Comment by palkan** [comment]
Hi @cskaandorp,

If your max is 1k then I suggest to start with the built-in Action Cable and see how it's going.

>  I have failed to get it to work.

It would be great if you share particular problems you encountered, so we'll be able to improve the docs.

**Comment by cskaandorp** [comment]
Hey @palkan, 

I would me more than willing to share my deployment issues with you. But as I've said, I try to set something up that I don't completely understand.

I have followed the description on [https://docs.anycable.io/#/heroku](https://docs.anycable.io/#/heroku). I have created the bin script. Speaking of which! I've managed to solve one issue due to a typo in your bin-file code:

```
#!/bin/bash

if [ "$ANYCABLE_DEPLOYMENT" == "true" ]; then
  ###!!! --server-comand should be --server-command !!!###
  bundle exec anycable --server-comand="anycable-go"
else
  bundle exec rails server -p $PORT -b 0.0.0.0  
fi
```
 added the Procfile, my cable.yml looks like this:

```
development:
  adapter: redis
  url: redis://localhost:6379/1

test:
  adapter: redis
  url: redis://localhost:6379/1

production:
  adapter: any_cable
```
Since I am using Devise I stuck to the code you've provided on [https://docs.anycable.io/#/using_with_rails?id=devise-authentication](https://docs.anycable.io/#/using_with_rails?id=devise-authentication) and my channel file looks like this:

```
class NetChannel < ApplicationCable::Channel
  
  def subscribed
    # user gets a channel only if connected to a node in the network
    stream_from "net_channel_#{ current_user.node.id }" if current_user.node
  end

  def unsubscribed
  end
  
end
```

After I've found the type in the bin/heroku file the -rpc runs fine:

```
DEPRECATION WARNING: You're using default rpc_host configuration which starts AnyCable RPC
server on all available interfaces including external IPv4 and IPv6.
This is about to be changed to loopback interface only in future versions.

Please, consider switching to the loopback interface or set "[::]:50051"
explicitly in your configuration, if you want to continue with the current
behavior and supress this message.

See https://docs.anycable.io/#/configuration
INFO -- : RPC server is starting...
INFO -- : RPC server is listening on [::]:50051
INFO -- : Started command: anycable-go (pid: 47)
context=main Starting AnyCable v0.6.0 (pid: 47)
context=main Handle WebSocket connections at /cable
context=http Starting HTTP server at 0.0.0.0:9024
context=rpc RPC pool initialized: localhost:50051
context=pubsub Subscribed to Redis channel: __anycable__
```

Eventually I'd like to know how to solve the deprecation warning. But the real issue is in the web-app:
 
```
2019-03-19T07:59:38.052978+00:00 heroku[router]: at=info method=GET path="/cable" host=fakebook-compunist.herokuapp.com request_id=d273c4c1-1f20-4deb-ae49-f3cc1155bc75 fwd="83.81.114.14" dyno=web.1 connect=1ms service=4ms status=500 bytes=1808 protocol=https
2019-03-19T08:00:08.080424+00:00 heroku[router]: at=info method=GET path="/cable" host=fakebook-compunist.herokuapp.com request_id=9bb7ac32-fed0-4ed9-bbb3-0291e75be159 fwd="83.81.114.14" dyno=web.1 connect=0ms service=4ms status=500 bytes=1808 protocol=https
2019-03-19T07:57:03+00:00 app[heroku-redis]: source=REDIS addon=redis-acute-24366 sample#active-connections=2 sample#load-avg-1m=0.17 sample#load-avg-5m=0.14 sample#load-avg-15m=0.135 sample#read-iops=0 sample#write-iops=0.21008 sample#memory-total=15664272kB sample#memory-free=12718400kB sample#memory-cached=952916kB sample#memory-redis=329920bytes sample#hit-rate=1 sample#evicted-keys=0
2019-03-19T08:00:08.081649+00:00 app[web.1]: I, [2019-03-19T08:00:08.081516 #7]  INFO -- : [9bb7ac32-fed0-4ed9-bbb3-0291e75be159] Started GET "/cable" for 83.81.114.14 at 2019-03-19 08:00:08 +0000
2019-03-19T08:00:08.082891+00:00 app[web.1]: F, [2019-03-19T08:00:08.082814 #7] FATAL -- : [9bb7ac32-fed0-4ed9-bbb3-0291e75be159]
2019-03-19T08:00:08.082944+00:00 app[web.1]: F, [2019-03-19T08:00:08.082889 #7] FATAL -- : [9bb7ac32-fed0-4ed9-bbb3-0291e75be159] ArgumentError (wrong number of arguments (given 2, expected 1)):
2019-03-19T08:00:08.083011+00:00 app[web.1]: F, [2019-03-19T08:00:08.082942 #7] FATAL -- : [9bb7ac32-fed0-4ed9-bbb3-0291e75be159]
2019-03-19T08:00:08.083128+00:00 app[web.1]: F, [2019-03-19T08:00:08.083045 #7] FATAL -- : [9bb7ac32-fed0-4ed9-bbb3-0291e75be159] vendor/bundle/ruby/2.4.0/gems/anycable-rails-0.6.2/lib/anycable/rails/actioncable/connection.rb:34:in `initialize'
```

Don't know where to look and what to do with the sixth line. Would very much appreciate your help.

C

**Comment by cskaandorp** [comment]
Hi @palkan, 

Sorry to bother you again, but I have less than a week to either get anycable working or to opt for a standard solution. If you are too busy: please let me know. I hate doing this, but I see the deadline racing towards me. Thanks!

C

**Comment by palkan** [comment]
Hi!

> If you are too busy: please let me know.

Let's try to figure this out today)

> I've managed to solve one issue due to a typo in your bin-file code:

Thanks for catching! Fixed in https://github.com/anycable/docs.anycable.io/commit/161631f9647790f2dae704f743982b839951162f

> Eventually I'd like to know how to solve the deprecation warning

The simplest way is to set `ANYCABLE_RPC_HOST=[::]:50051` env var in the RPC app.

> ArgumentError (wrong number of arguments (given 2, expected 1)):

As I see you try to connect to `fakebook-compunist.herokuapp.com` – is this your web app or RPC app?

This error usually occurs when you try to connect to the built-in Action Cable server while using AnyCable.

What do you have in your `config.action_cable.url`?

**Comment by cskaandorp** [comment]
Thanks, appreciate it!

`fakebook-compunist.herokuapp.com` is the web-app, `fakebook-rpc.herokuapp.com` is the RPC-app.

Ok, so the idiot starts to shine here...

In production.rb I've got this:
```
config.action_cable.url = ENV['CABLE_URL']
config.action_cable.allowed_request_origins = ['https://fakebook-compunist.herokuapp.com', 'https://fakebook-rpc.herokuapp.com']
```

And I haven't got defined ENV['CABLE_URL'] in the Heroku dashboard. What should it be? `https://fakebook-rpc.herokuapp.com`?

cheers

C

**Comment by palkan** [comment]
It should be `wss://fakebook-rpc.herokuapp.com/cable` – the URL of your RPC + anycable-go (WS) server

**Comment by cskaandorp** [comment]
The deprecation warning on the RPC app is gone.

I've set `CABLE_URL = wss://fakebook-rpc.herokuapp.com/cable` and have restarted the app. No joy:
```
heroku[web.1]: State changed from starting to up
heroku[router]: at=info method=GET path="/cable" host=fakebook-compunist.herokuapp.com request_id=43e5a6e6-dcb9-441f-9358-d09453bfec19 fwd="143.179.34.59" dyno=web.1 connect=0ms service=10ms status=500 bytes=1808 protocol=https
app[web.1]: I, [2019-03-22T16:31:01.567665 #7]  INFO -- : [43e5a6e6-dcb9-441f-9358-d09453bfec19] Started GET "/cable" for 143.179.34.59 at 2019-03-22 16:31:01 +0000
app[web.1]: F, [2019-03-22T16:31:01.572865 #7] FATAL -- : [43e5a6e6-dcb9-441f-9358-d09453bfec19]
app[web.1]: F, [2019-03-22T16:31:01.573131 #7] FATAL -- : [43e5a6e6-dcb9-441f-9358-d09453bfec19] ArgumentError (wrong number of arguments (given 2, expected 1)):
app[web.1]: F, [2019-03-22T16:31:01.573231 #7] FATAL -- : [43e5a6e6-dcb9-441f-9358-d09453bfec19]
app[web.1]: F, [2019-03-22T16:31:01.573335 #7] FATAL -- : [43e5a6e6-dcb9-441f-9358-d09453bfec19] vendor/bundle/ruby/2.4.0/gems/anycable-rails-0.6.2/lib/anycable/rails/actioncable/connection.rb:34:in `initialize'
app[web.1]: [43e5a6e6-dcb9-441f-9358-d09453bfec19] vendor/bundle/ruby/2.4.0/gems/actioncable-5.2.2.1/lib/action_cable/server/base.rb:30:in `new'
```

I have checked if the RPC server responds on websocket.org, I tried to connect and get disconnected immediately. The logs of RPC server reflects this. 

What the RPC logs don't show are any attempts of fakebook-compunist to reach the RPC server.

**Comment by palkan** [comment]
As you see from the logs your client still connects to the web server, not rpc.

How do you configure your client?

> What the RPC logs don't show are any attempts of fakebook-compunist to reach the RPC server.

I've just tried to connect to the server and got "Internal server error". Do you see anything in the logs?

**Comment by palkan** [comment]
> should I've put a url in here as well?

Your Redis URL)

AnyCable uses `REDIS_URL` env by default, if any. So if you have one – you're good.

**Comment by cskaandorp** [comment]
I guess this is you:

```
2019-03-22T17:28:36.156514+00:00 app[web.1]: 
2019-03-22T17:28:38.324466+00:00 heroku[router]: at=info method=GET path="/cable" host=fakebook-rpc.herokuapp.com request_id=a5fbf4ef-6f47-4a11-bdd8-cced6812291d fwd="71.190.217.247" dyno=web.1 connect=1ms service=19ms status=101 bytes=129 protocol=https
2019-03-22T17:28:38.307662+00:00 app[web.1]: D, [2019-03-22T17:28:38.307409 #7] DEBUG -- : [AnyCable sid=PUmu2uMnAmTbPbPGfsE2lp] RPC Connect: <AnyCable::ConnectionRequest: path: "/cable", headers: {"cookie"=>""}>
2019-03-22T17:28:38.323042+00:00 app[web.1]: E, [2019-03-22T17:28:38.322901 #7] ERROR -- : [AnyCable sid=PUmu2uMnAmTbPbPGfsE2lp] An unauthorized connection attempt was rejected
```

As for your other question ('how did you configure your client'): I just tried to follow your directions in the docs. And this is obviously not answering your question. Could you please be a bit more specific? Thanks for your patience.

**Comment by cskaandorp** [comment]
Which part of the app is responsible for asking the web-version of /cable..?

**Comment by palkan** [comment]
> I guess this is you:

yeah, looks like everything is fine.

> Which part of the app is responsible for asking the web-version of /cable..?

This question is about JS client (do you use the default JS one?): how do you initialize your _consumer_? (via `createConsumer()`)
Do you have `action_cable_meta_tag` (and if do, what is the generated HTML?)

**Comment by palkan** [comment]
> The RPC server has a REDIS_URL so that's good.

Make sure you have the same value in the web app

**Comment by cskaandorp** [comment]
REDIS_URL's are the same

Maybe unimportant, but should the SECRET_KEY_BASE be the same as well?

I've added the meta tag, here's the result:
`<meta name="action-cable-url" content="wss://fakebook-rpc.herokuapp.com/cable">`

Looks fine right!?

Everything is Vanilla ActionCable... cable.js:
```
//= require action_cable
//= require_self
//= require_tree ./channels

(function() {
  this.App || (this.App = {});

  App.cable = ActionCable.createConsumer();

}).call(this);
```

**Comment by palkan** [comment]
> Maybe unimportant, but should the SECRET_KEY_BASE be the same as well?

Yeah, it should be.

> Looks fine right!?

Right.

What is the order of `action_cable_meta_tag` and `javascript_include_tag` in your HTML? Maybe, `App.cable` is initializing before the meta tag appears (and uses the default "/cable" url).

Also, could you try to add URL explicitly (just to check): `ActionCable.createConsumer("wss://fakebook-rpc.herokuapp.com/cable")`;

**Comment by cskaandorp** [comment]
Ok, it seems the plot starts to thicken.

I had two different SECRET_KEY_BASE values. This was probably stupid, but I strictly tried to follow [https://docs.anycable.io/#/heroku](https://docs.anycable.io/#/heroku) and I can't find any text on that. Anyways, if you would like to make your text idiot-proof... ;)

There is life at the RPC server, now it says every 30 secs or so:
```
2019-03-22T19:06:03.623711+00:00 heroku[router]: at=info method=GET path="/cable" host=fakebook-rpc.herokuapp.com request_id=c9081e9e-36a2-4572-9738-3a1123c1d407 fwd="143.179.34.59" dyno=web.1 connect=1ms service=11ms status=101 bytes=174 protocol=https
2019-03-22T19:06:03.618407+00:00 app[web.1]: D, [2019-03-22T19:06:03.618255 #7] DEBUG -- : [AnyCable sid=gNBDVjWLUBJTRR6InRllQN] RPC Connect: <AnyCable::ConnectionRequest: path: "/cable", headers: {"cookie"=>""}>
2019-03-22T19:06:03.619049+00:00 app[web.1]: E, [2019-03-22T19:06:03.618970 #7] ERROR -- : [AnyCable sid=gNBDVjWLUBJTRR6InRllQN] An unauthorized connection attempt was rejected
```

**Comment by palkan** [comment]
> Anyways, if you would like to make your text idiot-proof... ;)

This guide is not that good, no worries, it definitely needs updates (I'll add a link to this issue as soon as we make it work).

> There is life at the RPC server, now it says every 30 secs or so:

That's good.
You can see that `"cookies"` is empty.
That's likely due to the cross-domain cookies sharing problem.

We have this situation covered in the docs: https://docs.anycable.io/#/heroku?id=my-websocket-connection-fails-with-quotauth-failedquot-error.

Unfortunately, since you're suing `.herokuapp.com` domains, you won't be able to share the cookies( https://devcenter.heroku.com/articles/cookies-and-herokuapp-com

The workaround is to use cookie-less authentication (e.g. JWT tokens).

**Comment by cskaandorp** [comment]
Yes, I've seen it.

Haven't seen or used this since I've started with Rails. And we're talking 2001. I need a bit more guidance than the text. 

As I understand session_store.rb is gone in Rails 5. So I've created one in config/initializers and put your contents in it:
```
# session_store.rb
Rails.application.config.session_store :cookie_store,
    key: '_any_cable_session',
    domain: :all # or domain: '.example.com'

# anywhere setting cookie
cookies[:val] = { value: '1', domain: :all }
```

But when I deploy I get this: `NameError: undefined local variable or method `cookie' for main:Object`

So I guess it is the last line of code, where should I put that...

And is this going to give me Devise problems?

**Comment by cskaandorp** [comment]
Oh damn! You mean, this is not going to work anyway unless I start using a real domain name right? Ok, I will start using a real domain instead of a Heroku subdomain. But my former question still stands, where do I put `cookies[:val] = { value: '1', domain: :all }`?

**Comment by palkan** [comment]
I suggest to checking this doc: https://github.com/plataformatec/devise/wiki/How-To:-Use-subdomains

**Comment by cskaandorp** [comment]
I'm sorry man, but I can't connect the dots here. I've created 2 subdomains and started from scratch. One subdomain for the RPC, the other for the Web app.

In the Procfile I had this:
`web: CABLE_URL='wss://networkrpc.compunist.nl/cable' bin/heroku`

And that did nothing, the RPC server didn't get requests anymore, total silence. 

Changing that to:
`web: CABLE_URL='wss://networkrpc-compunist-nl.herokuapp.com/cable' bin/heroku`

brought the whole thing to life, but since I am using two different domains I got the unauthorized request issue again:
```
2019-03-23T21:57:10.217805+00:00 app[web.1]: D, [2019-03-23T21:57:10.217667 #7] DEBUG -- : [AnyCable sid=ftxcA0uLuTm2B0heha9QwR] RPC Connect: <AnyCable::ConnectionRequest: path: "/cable", headers: {"cookie"=>""}>
```

Apparently I am doing something wrong with the subdomains but haven't got a clue what to do now. Look, I can imagine this is a bit annoying, and maybe github is not the place to fix this. At this stage I am willing to pay you if that will speed up things. You're trying to help a passenger landing a Boeing 747.

**Comment by cskaandorp** [comment]
Hi @palkan, 

Thanks for trying to help me out, but since the deadline is coming up and since the load of 1000 concurrent users wont be that taxing (I hope), I am going to bail out on this. I would have loved to use it, but I get the feeling that Heroku is not the best place to deploy anycable. I'd rather would like to try it on Digital Ocean, but I have a lot of work (no time to fiddle around with a server), so I will gamble on a vanilla action-cable implementation on Heroku.

**Comment by nmenag** [comment]
@palkan 

I am having the same problem, I don't  understand what is the rpc_host, my project is built in Rails and I have installed the gem, I have built two apps, one added the buildpack of anycable-go, in my configuration de anycable.yml: 

```ruby
# This file contains per-environment settings for AnyCable.
#
# Since AnyCable config is based on anyway_config (https://github.com/palkan/anyway_config), all AnyCable settings
# can be set or overridden through the corresponding environment variables.
# E.g., `rpc_host` is overridden by ANYCABLE_RPC_HOST, `debug` by ANYCABLE_DEBUG etc.
#
# Note that AnyCable recognizes REDIS_URL env variable for Redis pub/sub adapter. If you want to
# use another Redis instance for AnyCable, provide ANYCABLE_REDIS_URL variable.
#
# Read more about AnyCable configuration here: https://docs.anycable.io/#/ruby/configuration
#
default: &default
  # Turn on/off access logs ("Started..." and "Finished...")
  access_logs_disabled: false
  # Persist "dirty" session between RPC calls (might be required for StimulusReflex apps)
  persistent_session_enabled: true
  # This is the host and the port to run AnyCable RPC server on.
  # You must configure your WebSocket server to connect to it, e.g.:
  #   $ anycable-go --rpc-host="<rpc hostname>:50051"
  rpc_host: 'example-app-anycable.herokuapp.com:50051'
  # Whether to enable gRPC level logging or not
  log_grpc: false
  # Use the same channel name for WebSocket server, e.g.:
  #   $ anycable-go --redis-channel="__anycable__"
  redis_channel: "__anycable__"

stage:
  <<: *default
  redis_url: <%= ENV.fetch("REDISCLOUD_URL") { "redis://localhost:6379/1" } %>

production:
  <<: *default
  redis_url: <%= ENV.fetch("REDISCLOUD_URL") { "redis://localhost:6379/1" } %>
```

I am following the documentation, https://docs.anycable.io/v06/#/deployment/heroku

example-app-anycable has the buildpack but is an app empty and the attach of redis and postgres from  main  app. I understand that the two apps is using the same procfile.

the traceback on Heroku logs: 

```"os_error":"Cannot assign requested address","syscall":"bind"}]}]}
2020-05-20T17:11:30.840622+00:00 app[web.1]: could not add port example-app-anycable.herokuapp.com:50051 to server, not sure why
2020-05-20T17:11:30.840719+00:00 app[web.1]: /app/vendor/ruby-2.6.2/lib/ruby/2.6.0/forwardable.rb:230:in `add_http2_port'
2020-05-20T17:11:30.840720+00:00 app[web.1]: /app/vendor/ruby-2.6.2/lib/ruby/2.6.0/forwardable.rb:230:in `add_http2_port
```
