### ISSUE TITLE
Redis dependency causing loading error

### ISSUE THREAD

**Issue by yoonwaiyan** [anycable/anycable#85]
### Tell us about your environment

**Ruby version:** 2.4.2

**`anycable` gem version:** 0.6.2

**`grpc` gem version:** 1.19.0

### What did you do?
I'm trying to broadcast a message from one rails app (with custom loaders so that it only work as a backend server) to another rails app.

### What did you expect to happen?
Expecting it to broadcast message without any error

### What actually happened?
There's an error while broadcasting to another rails app. The error I received was `Gem::LoadError: Error loading the 'redis' broadcast adapter for AnyCable`, which I took some while to trace it back to anycable gem instead of anycable-rails. This is the error message I get: `#<Gem::LoadError: can't activate redis (>= 4.0), already activated redis-3.3.5. Make sure all dependencies are added to Gemfile.>`

I saw this line on top of the file in `lib/anycable/broadcast_adapters/redis.rb` 
```ruby
gem "redis", ">= 4.0"
```
This raised error because the redis version installed in the rails app is 3.3.5. Maybe upgrading the gem version could work but we don't want to put anything else at risk. Is it possible to better manage the gem, at least putting it as part of the dependency, best if redis version 3.3.5 is supported? We're using anycable in out receiving end also, maybe an older version of anycable gems, but it works without this hassle.

**Comment by sponomarev** [comment]
@palkan We can easily relax the dependence to the same constraints that ActionCable has.  WDYT?

https://github.com/rails/rails/blob/08a435fa8c2307e78436eeaad43bfae7a54b2ab4/actioncable/lib/action_cable/subscription_adapter/redis.rb#L5

**Comment by palkan** [comment]
> We can easily relax the dependence to the same constraints that ActionCable has. WDYT?

Sure, we can. I'll do.

**Comment by palkan** [comment]
Released as 0.6.3.
