### ISSUE TITLE
Auth failed with devise_token_auth

### ISSUE THREAD

**Issue by FlorianGerhardt** [anycable/anycable#9]
Hey there!
I can't establish a connection when using the authentication gem devise_token_auth.
I try to identify the user like this:

`
module ApplicationCable
  class Connection < ActionCable::Connection::Base
    identified_by :current_user
    identified_by :device

    def connect
      self.current_user = find_verified_user
      self.device = Device.find(request.params[:device_id])
    end

    def disconnect
    end

    def find_verified_user
      logger.error request.params.inspect
      user = request.params[:uid].present? && User.find_by_uid(request.params[:uid])
      if user && user.valid_token?(request.params[:"access-token"], request.params[:client])
        logger.error "Success"
        return user
      else
        user = nil
        reject_unauthorized_connection
      end
    end

  end
end

`

and anycable-go gives me "Auth failed".

Params are getting through, the device is getting loaded but it never stays connected. When I change 
      self.current_user = find_verified_user     to       self.current_user = User.find(request.params[:user_id])
it keeps the connection alive.

When logging the params connection.rb gets, it seems like anycable is somehow stalling or something the requests: http://pastebin.com/w6NtPd5U

**Comment by palkan** [comment]
Have you checked whether the problem is with token or uid?
I mean, have you tried to add logger here:

```ruby
def find_verified_user
  user = request.params[:uid].present? && User.find_by_uid(request.params[:uid])
  logger.error user
  if user && user.valid_token?(request.params[:"access-token"], request.params[:client])
    logger.error "Success"
    return user
  else
    user = nil
    reject_unauthorized_connection
  end
end
```

Also, can you log each parameter independently and without inspect? That is:

```ruby
logger.error request.params[:"access-token"]
logger.error request.params[:uid]
...
```

**Comment by FlorianGerhardt** [comment]
Params are all fine, I also get a user. The problem is with the stalling, I don't get a connection but also no error. anycable-go throws me this error:

`RPC Error: rpc error: code = 2 desc = ActiveRecord::ConnectionTimeoutError: could not obtain a connection from the pool within 5.000 seconds (waited 5.000 seconds); all pooled connections were in use
2017/02/22 16:33:49 http: panic serving 178.19.210.162:55103: runtime error: invalid memory address or nil pointer dereference
goroutine 292 [running]:
net/http.(*conn).serve.func1(0xc820364c00)
        /usr/local/Cellar/go/1.6.2/libexec/src/net/http/server.go:1389 +0xc1
panic(0x8fa2a0, 0xc82000a080)
        /usr/local/Cellar/go/1.6.2/libexec/src/runtime/panic.go:443 +0x4e9
main.serveWs(0x7f0ae5992920, 0xc82044c680, 0xc820370380)
        /Users/palkan/lib/go/src/github.com/anycable/anycable-go/server.go:137 +0x254
net/http.HandlerFunc.ServeHTTP(0xa93d28, 0x7f0ae5992920, 0xc82044c680, 0xc820370380)
        /usr/local/Cellar/go/1.6.2/libexec/src/net/http/server.go:1618 +0x3a
net/http.(*ServeMux).ServeHTTP(0xc820046c30, 0x7f0ae5992920, 0xc82044c680, 0xc820370380)
        /usr/local/Cellar/go/1.6.2/libexec/src/net/http/server.go:1910 +0x17d
net/http.serverHandler.ServeHTTP(0xc820065280, 0x7f0ae5992920, 0xc82044c680, 0xc820370380)
        /usr/local/Cellar/go/1.6.2/libexec/src/net/http/server.go:2081 +0x19e
net/http.(*conn).serve(0xc820364c00)
        /usr/local/Cellar/go/1.6.2/libexec/src/net/http/server.go:1472 +0xf2e
created by net/http.(*Server).Serve
        /usr/local/Cellar/go/1.6.2/libexec/src/net/http/server.go:2137 +0x44e
`

**Comment by FlorianGerhardt** [comment]
So after setting rpc and anycable-go to debug mode, I get some new errors:

RPC:
`D, [2017-02-23T09:02:02.447924 #1] DEBUG -- : Sending status  2:ActiveRecord::ConnectionTimeoutError: could not obtain a connection from the pool within 5.000 seconds (waited 5.000 seconds); all pooled connections were in use
W, [2017-02-23T09:02:03.443438 #1]  WARN -- : failed handler: #<GRPC::ActiveCall:0x00000004c4af50>; sending status:UNKNOWN
W, [2017-02-23T09:02:03.443543 #1]  WARN -- : could not obtain a connection from the pool within 5.000 seconds (waited 5.000 seconds); all pooled connections were in use (ActiveRecord::ConnectionTimeoutError)
/usr/local/rvm/gems/ruby-2.4.0/gems/activerecord-5.0.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:202:in `block in wait_poll'
/usr/local/rvm/gems/ruby-2.4.0/gems/activerecord-5.0.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:193:in `loop'
/usr/local/rvm/gems/ruby-2.4.0/gems/activerecord-5.0.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:193:in `wait_poll'
/usr/local/rvm/gems/ruby-2.4.0/gems/activerecord-5.0.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:154:in `internal_poll'
/usr/local/rvm/gems/ruby-2.4.0/gems/activerecord-5.0.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:278:in `internal_poll'
/usr/local/rvm/gems/ruby-2.4.0/gems/activerecord-5.0.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:148:in `block in poll'
/usr/local/rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
/usr/local/rvm/gems/ruby-2.4.0/gems/activerecord-5.0.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:158:in `synchronize'
/usr/local/rvm/gems/ruby-2.4.0/gems/activerecord-5.0.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:148:in `poll'
/usr/local/rvm/gems/ruby-2.4.0/gems/activerecord-5.0.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:717:in `acquire_connection'
/usr/local/rvm/gems/ruby-2.4.0/gems/activerecord-5.0.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:490:in `checkout'
/usr/local/rvm/gems/ruby-2.4.0/gems/activerecord-5.0.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:364:in `connection'
/usr/local/rvm/gems/ruby-2.4.0/gems/activerecord-5.0.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:883:in `retrieve_connection'
/usr/local/rvm/gems/ruby-2.4.0/gems/activerecord-5.0.1/lib/active_record/connection_handling.rb:128:in `retrieve_connection'
/usr/local/rvm/gems/ruby-2.4.0/gems/activerecord-5.0.1/lib/active_record/connection_handling.rb:91:in `connection'
/usr/local/rvm/gems/ruby-2.4.0/gems/activerecord-5.0.1/lib/active_record/core.rb:283:in `cached_find_by_statement'
/usr/local/rvm/gems/ruby-2.4.0/gems/activerecord-5.0.1/lib/active_record/core.rb:196:in `find_by'
/usr/local/rvm/gems/ruby-2.4.0/gems/activerecord-5.0.1/lib/active_record/dynamic_matchers.rb:65:in `find_by_uid'
/home/app/skill_hero_api/app/channels/application_cable/connection.rb:15:in `find_verified_user'
/home/app/skill_hero_api/app/channels/application_cable/connection.rb:7:in `connect'
/usr/local/rvm/gems/ruby-2.4.0/gems/anycable-rails-0.4.3/lib/anycable/rails/actioncable/connection.rb:42:in `handle_open'
/usr/local/rvm/gems/ruby-2.4.0/gems/anycable-0.4.3/lib/anycable/rpc_handler.rb:19:in `connect'
/usr/local/rvm/gems/ruby-2.4.0/gems/grpc-1.1.2-x86_64-linux/src/ruby/lib/grpc/generic/rpc_desc.rb:67:in `call'
/usr/local/rvm/gems/ruby-2.4.0/gems/grpc-1.1.2-x86_64-linux/src/ruby/lib/grpc/generic/rpc_desc.rb:67:in `handle_request_response'
/usr/local/rvm/gems/ruby-2.4.0/gems/grpc-1.1.2-x86_64-linux/src/ruby/lib/grpc/generic/rpc_desc.rb:95:in `run_server_method'
/usr/local/rvm/gems/ruby-2.4.0/gems/grpc-1.1.2-x86_64-linux/src/ruby/lib/grpc/generic/rpc_server.rb:392:in `block in loop_handle_server_calls'
/usr/local/rvm/gems/ruby-2.4.0/gems/grpc-1.1.2-x86_64-linux/src/ruby/lib/grpc/generic/rpc_server.rb:149:in `block in loop_execute_jobs'
/usr/local/rvm/gems/ruby-2.4.0/gems/grpc-1.1.2-x86_64-linux/src/ruby/lib/grpc/generic/rpc_server.rb:146:in `loop'
/usr/local/rvm/gems/ruby-2.4.0/gems/grpc-1.1.2-x86_64-linux/src/ruby/lib/grpc/generic/rpc_server.rb:146:in `loop_execute_jobs'
/usr/local/rvm/gems/ruby-2.4.0/gems/grpc-1.1.2-x86_64-linux/src/ruby/lib/grpc/generic/rpc_server.rb:99:in `block (2 levels) in start'
/usr/local/rvm/gems/ruby-2.4.0/gems/grpc-1.1.2-x86_64-linux/src/ruby/lib/grpc/generic/rpc_server.rb:98:in `catch'
/usr/local/rvm/gems/ruby-2.4.0/gems/grpc-1.1.2-x86_64-linux/src/ruby/lib/grpc/generic/rpc_server.rb:98:in `block in start'
`
and anycable-go:
`Auth status:SUCCESS identifiers:"{\"current_user\":\"Z2lkOi8vYXBpL1VzZXIvMQ\",\"device\":\"Z2lkOi8vYXBpL0RldmljZS8x\"}" transmissions:"{\"type\":\"welcome\"}"
Register connection &{0xc8200a7f00 {"current_user":"Z2lkOi8vYXBpL1VzZXIvMQ","device":"Z2lkOi8vYXBpL0RldmljZS8x"} map[] 0xc8201d3320}
Broadcast message {"type":"ping","identifier":"","message":1487840351}
Broadcast message {"type":"ping","identifier":"","message":1487840354}
Broadcast message {"type":"ping","identifier":"","message":1487840357}
Broadcast message {"type":"ping","identifier":"","message":1487840360}
Broadcast message {"type":"ping","identifier":"","message":1487840363}
Broadcast message {"type":"ping","identifier":"","message":1487840366}
Broadcast message {"type":"ping","identifier":"","message":1487840369}
Broadcast message {"type":"ping","identifier":"","message":1487840372}
Broadcast message {"type":"ping","identifier":"","message":1487840375}
Broadcast message {"type":"ping","identifier":"","message":1487840378}
Broadcast message {"type":"ping","identifier":"","message":1487840381}
Broadcast message {"type":"ping","identifier":"","message":1487840384}
Client message: &{subscribe {"channel":"UserChannel"} }
Broadcast message {"type":"ping","identifier":"","message":1487840387}
RPC Error: rpc error: code = 12 desc =
Disconnect on read error
Pause ping
2017/02/23 08:59:47 http: panic serving 178.19.210.162:51724: runtime error: invalid memory address or nil pointer dereference
goroutine 98 [running]:
net/http.(*conn).serve.func1(0xc8201ab800)
        /usr/local/Cellar/go/1.6.2/libexec/src/net/http/server.go:1389 +0xc1
panic(0x8fa2a0, 0xc82000a080)
        /usr/local/Cellar/go/1.6.2/libexec/src/runtime/panic.go:443 +0x4e9
main.(*App).Subscribe(0xc5efc0, 0xc82022e5a0, 0xc82022e990)
        /Users/palkan/lib/go/src/github.com/anycable/anycable-go/app.go:58 +0x1e1
main.(*Conn).readPump(0xc82022e5a0)
        /Users/palkan/lib/go/src/github.com/anycable/anycable-go/server.go:82 +0x5c1
main.serveWs(0x7f12c5064980, 0xc82021eb60, 0xc820114b60)
        /Users/palkan/lib/go/src/github.com/anycable/anycable-go/server.go:146 +0x432
net/http.HandlerFunc.ServeHTTP(0xa93d28, 0x7f12c5064980, 0xc82021eb60, 0xc820114b60)
        /usr/local/Cellar/go/1.6.2/libexec/src/net/http/server.go:1618 +0x3a
net/http.(*ServeMux).ServeHTTP(0xc820046c30, 0x7f12c5064980, 0xc82021eb60, 0xc820114b60)
        /usr/local/Cellar/go/1.6.2/libexec/src/net/http/server.go:1910 +0x17d
net/http.serverHandler.ServeHTTP(0xc820065280, 0x7f12c5064980, 0xc82021eb60, 0xc820114b60)
        /usr/local/Cellar/go/1.6.2/libexec/src/net/http/server.go:2081 +0x19e
net/http.(*conn).serve(0xc8201ab800)
        /usr/local/Cellar/go/1.6.2/libexec/src/net/http/server.go:1472 +0xf2e
created by net/http.(*Server).Serve
        /usr/local/Cellar/go/1.6.2/libexec/src/net/http/server.go:2137 +0x44e
Unregister connection &{0xc8200a7f00 {"current_user":"Z2lkOi8vYXBpL1VzZXIvMQ","device":"Z2lkOi8vYXBpL0RldmljZS8x"} map[] 0xc8201d3320}
Unsubscribe from all streams: {"current_user":"Z2lkOi8vYXBpL1VzZXIvMQ","device":"Z2lkOi8vYXBpL0RldmljZS8x"}
Ping paused
`

I get a stable connection but as soon as I try to subscribe a channel, I get disconnected and am unable to connect again.

**Comment by palkan** [comment]
`anycable-go` error is caused by RPC error, which in its turn caused by ActiveRecord timeout. Looks like for some reason AR connection are not released. I'll try to reproduce this and fix ASAP.

Do you have AR calls in your channels, e.g. in `#subscribed` callback?

**Comment by FlorianGerhardt** [comment]
My UserChannel looks like this:
`class UserChannel < ApplicationCable::Channel
  def subscribed
    stream_from 'user_channel-' + current_user.uid
  end

  def unsubscribed
    if device
      device.last_sync = Time.now.to_datetime
      device.save
    end
  end
end`

**Comment by palkan** [comment]
I hope that would be enough to reproduce the bug. Thanks!

**Comment by palkan** [comment]
Please, use `anycable-rails` 0.4.4, which fixes the bug.
